import type { L, Tour } from "./data";

/**
 * 2026 brochure catalogue — transcribed from the agency PDF programmes in
 * `/public/voyages`. Prices are the published "à partir de" (triple room,
 * per person, MAD). Nothing here is invented: when a figure is absent from the
 * brochure the field is simply omitted rather than filled in.
 */

const TURQUIE: L = { fr: "Turquie", ar: "تركيا" };
const EGYPTE: L = { fr: "Égypte", ar: "مصر" };
const BALKANS: L = { fr: "Balkans", ar: "البلقان" };
const CHINE: L = { fr: "Chine", ar: "الصين" };
const ROYAUME_UNI: L = { fr: "Royaume-Uni", ar: "المملكة المتحدة" };
const ITALIE: L = { fr: "Italie", ar: "إيطاليا" };

const CASABLANCA: L = { fr: "Casablanca", ar: "الدار البيضاء" };

/** Clauses repeated verbatim across every programme. */
const EXTRAS_NON_INCLUS: L = {
  fr: "Les extras, les pourboires et tout ce qui n'est pas mentionné au programme",
  ar: "المصاريف الإضافية والإكراميات وكل ما لم يُذكر في البرنامج",
};

export const voyages2026: Tour[] = [
  /* ====================================================================== */
  /*  TURQUIE                                                               */
  /* ====================================================================== */
  {
    id: "istanbul-2026",
    slug: "istanbul-ete-2026",
    zone: TURQUIE,
    kind: "sejour",
    title: { fr: "Istanbul, la ville aux deux continents", ar: "إسطنبول، مدينة القارّتين" },
    summary: {
      fr: "Sept nuits au cœur d'Istanbul, croisière sur le Bosphore incluse et journées libres pour explorer la ville à votre rythme.",
      ar: "سبع ليالٍ في قلب إسطنبول، مع رحلة بحرية في البوسفور وأيام حرّة لاكتشاف المدينة على إيقاعك.",
    },
    region: { fr: "Istanbul", ar: "إسطنبول" },
    days: 8,
    nights: 7,
    priceMad: 11300,
    image: "/media/tours/istanbul.webp",
    level: { fr: "Séjour ville", ar: "إقامة مدينة" },
    best: { fr: "Juillet – Août 2026", ar: "يوليوز – غشت 2026" },
    flightIncluded: true,
    airline: "Turkish Airlines",
    departureCity: CASABLANCA,
    departures: [
      { fr: "25/07 → 01/08/2026", ar: "25/07 → 01/08/2026" },
      { fr: "02/08 → 09/08/2026", ar: "02/08 → 09/08/2026" },
      { fr: "03/08 → 10/08/2026", ar: "03/08 → 10/08/2026" },
      { fr: "08/08 → 15/08/2026", ar: "08/08 → 15/08/2026" },
      { fr: "09/08 → 16/08/2026", ar: "09/08 → 16/08/2026" },
      { fr: "14/08 → 21/08/2026", ar: "14/08 → 21/08/2026" },
      { fr: "16/08 → 23/08/2026", ar: "16/08 → 23/08/2026" },
      { fr: "22/08 → 29/08/2026", ar: "22/08 → 29/08/2026" },
      { fr: "23/08 → 30/08/2026", ar: "23/08 → 30/08/2026" },
    ],
    highlights: [
      { fr: "Croisière sur le Bosphore incluse", ar: "رحلة بحرية في البوسفور مشمولة" },
      { fr: "Vol direct Turkish Airlines", ar: "رحلة مباشرة مع الخطوط التركية" },
      { fr: "Mosquée Bleue, Sainte-Sophie et Grand Bazar à deux pas", ar: "المسجد الأزرق وآيا صوفيا والبازار الكبير على مقربة" },
      { fr: "Excursions à la carte : Bursa, Îles des Princes, Sapanca", ar: "رحلات اختيارية: بورصة، جزر الأميرات، سابانجا" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Casablanca – Istanbul", ar: "الدار البيضاء – إسطنبول" }, detail: { fr: "Envol pour Istanbul, accueil par notre correspondant et transfert à l'hôtel. Dîner libre et nuit.", ar: "الإقلاع نحو إسطنبول، استقبال من مندوبنا والنقل إلى الفندق. عشاء حرّ ومبيت." } },
      { day: 2, title: { fr: "Croisière sur le Bosphore", ar: "رحلة بحرية في البوسفور" }, detail: { fr: "Croisière sur le Bosphore puis temps libre au centre commercial Olivium. Retour et nuit à l'hôtel.", ar: "رحلة بحرية في البوسفور ثم وقت حرّ في مركز أوليفيوم التجاري. العودة والمبيت بالفندق." } },
      { day: 3, title: { fr: "Istanbul – journée libre", ar: "إسطنبول – يوم حرّ" }, detail: { fr: "Journée libre : Mosquée Bleue, Sainte-Sophie, Grand Bazar ou flânerie dans les rues animées.", ar: "يوم حرّ: المسجد الأزرق، آيا صوفيا، البازار الكبير أو تجوّل في الشوارع النابضة." } },
      { day: 4, title: { fr: "Dîner-spectacle sur le Bosphore (option)", ar: "عشاء وعرض على متن الباخرة (اختياري)" }, detail: { fr: "Croisière animée sur le Bosphore avec dîner et spectacle en direct.", ar: "رحلة بحرية مع عشاء وعروض حيّة على متن الباخرة." } },
      { day: 5, title: { fr: "City tour (option)", ar: "جولة في المدينة (اختياري)" }, detail: { fr: "Hippodrome, Mosquée Bleue aux six minarets et faïences d'Iznik, puis palais de Topkapi (extérieur).", ar: "الميدان، المسجد الأزرق بمآذنه الستّ وخزف إزنيك، ثم قصر طوب قابي (من الخارج)." } },
      { day: 6, title: { fr: "Îles des Princes (option)", ar: "جزر الأميرات (اختياري)" }, detail: { fr: "Archipel de la mer de Marmara, arrêt à Büyükada, tour de l'île en calèche et déjeuner au bord de la mer.", ar: "أرخبيل بحر مرمرة، توقّف في بويوك أضا، جولة بالعربة وغداء على شاطئ البحر." } },
      { day: 7, title: { fr: "Bursa (option)", ar: "بورصة (اختياري)" }, detail: { fr: "Route par Yalova, marché de la soie, Mosquée Verte et montée du mont Uludağ en téléphérique. Déjeuner barbecue au sommet.", ar: "الطريق عبر يالوفا، سوق الحرير، الجامع الأخضر وصعود جبل أولوداغ بالتلفريك. غداء مشوي في القمّة." } },
      { day: 8, title: { fr: "Istanbul – Casablanca", ar: "إسطنبول – الدار البيضاء" }, detail: { fr: "Transfert à l'aéroport pour le vol retour vers Casablanca.", ar: "النقل إلى المطار لرحلة العودة نحو الدار البيضاء." } },
    ],
    hotels: [
      { city: { fr: "Istanbul", ar: "إسطنبول" }, name: "Ramada by Wyndham Pera 5*", nights: 7 },
      { city: { fr: "Istanbul", ar: "إسطنبول" }, name: "Taksim Square 4*", nights: 7 },
    ],
    pricing: [
      { label: { fr: "Ramada Pera 5* · Triple", ar: "رمادا بيرا 5* · ثلاثية" }, mad: 11300 },
      { label: { fr: "Ramada Pera 5* · Double", ar: "رمادا بيرا 5* · مزدوجة" }, mad: 11950 },
      { label: { fr: "Ramada Pera 5* · Supplément single", ar: "رمادا بيرا 5* · زيادة الغرفة الفردية" }, mad: 3650 },
      { label: { fr: "Taksim Square 4* · Triple", ar: "تقسيم سكوير 4* · ثلاثية" }, mad: 12000 },
      { label: { fr: "Taksim Square 4* · Double", ar: "تقسيم سكوير 4* · مزدوجة" }, mad: 12750 },
      { label: { fr: "Taksim Square 4* · Supplément single", ar: "تقسيم سكوير 4* · زيادة الغرفة الفردية" }, mad: 4200 },
      { label: { fr: "Enfant de moins de 2 ans", ar: "طفل أقل من سنتين" }, mad: 600 },
      { label: { fr: "Enfant de 2 à 6 ans", ar: "طفل من 2 إلى 6 سنوات" }, mad: 6700 },
      { label: { fr: "Enfant de 7 à 11 ans (à partir de)", ar: "طفل من 7 إلى 11 سنة (ابتداءً من)" }, mad: 9650 },
    ],
    included: [
      { fr: "Vol direct Turkish Airlines en classe économique", ar: "رحلة مباشرة مع الخطوط التركية في الدرجة السياحية" },
      { fr: "7 nuits en chambre classique avec petit déjeuner", ar: "7 ليالٍ في غرفة عادية مع الفطور" },
      { fr: "Croisière sur le Bosphore", ar: "رحلة بحرية في البوسفور" },
      { fr: "Assistance d'un guide arabophone", ar: "مرافقة مرشد ناطق بالعربية" },
      { fr: "Transferts aéroport / hôtel / aéroport", ar: "التنقّلات مطار / فندق / مطار" },
    ],
    notIncluded: [
      EXTRAS_NON_INCLUS,
      { fr: "Les excursions optionnelles listées ci-dessous", ar: "الرحلات الاختيارية المذكورة أدناه" },
    ],
    options: [
      { label: { fr: "Tour de Bursa", ar: "جولة بورصة" }, mad: 660 },
      { label: { fr: "Tour de Sapanca", ar: "جولة سابانجا" }, mad: 550 },
      { label: { fr: "Visite de la ville avec Topkapi", ar: "زيارة المدينة مع طوب قابي" }, mad: 750 },
      { label: { fr: "Visite de la ville d'Istanbul", ar: "زيارة مدينة إسطنبول" }, mad: 250 },
      { label: { fr: "Îles des Princes avec déjeuner", ar: "جزر الأميرات مع الغداء" }, mad: 390 },
      { label: { fr: "Dîner-spectacle sur le bateau", ar: "عشاء وعرض على متن الباخرة" }, mad: 550 },
    ],
    flights: [
      { route: { fr: "Casablanca → Istanbul", ar: "الدار البيضاء ← إسطنبول" }, time: "16h50 – 23h30" },
      { route: { fr: "Istanbul → Casablanca", ar: "إسطنبول ← الدار البيضاء" }, time: "12h05 – 14h55" },
    ],
  },

  {
    id: "istanbul-antalya-2026",
    slug: "istanbul-antalya-ete-2026",
    zone: TURQUIE,
    kind: "sejour",
    title: { fr: "Istanbul & Antalya", ar: "إسطنبول وأنطاليا" },
    summary: {
      fr: "Trois nuits à Istanbul puis sept nuits en All Inclusive sur la Riviera turque, entre plages, marina et vieille ville de Kaleiçi.",
      ar: "ثلاث ليالٍ في إسطنبول ثم سبع ليالٍ بنظام الشامل على الريفييرا التركية، بين الشواطئ والمارينا ومدينة كاليتشي العتيقة.",
    },
    region: { fr: "Istanbul & Riviera turque", ar: "إسطنبول والريفييرا التركية" },
    days: 11,
    nights: 10,
    priceMad: 19750,
    image: "/media/tours/antalya.webp",
    level: { fr: "Séjour balnéaire", ar: "إقامة شاطئية" },
    best: { fr: "Juillet – Août 2026", ar: "يوليوز – غشت 2026" },
    flightIncluded: true,
    airline: "Turkish Airlines",
    departureCity: CASABLANCA,
    departures: [
      { fr: "23/07 → 02/08/2026", ar: "23/07 → 02/08/2026" },
      { fr: "24/07 → 03/08/2026", ar: "24/07 → 03/08/2026" },
      { fr: "30/07 → 09/08/2026", ar: "30/07 → 09/08/2026" },
      { fr: "31/07 → 10/08/2026", ar: "31/07 → 10/08/2026" },
      { fr: "06/08 → 16/08/2026", ar: "06/08 → 16/08/2026" },
      { fr: "07/08 → 17/08/2026", ar: "07/08 → 17/08/2026" },
      { fr: "13/08 → 23/08/2026", ar: "13/08 → 23/08/2026" },
      { fr: "14/08 → 24/08/2026", ar: "14/08 → 24/08/2026" },
      { fr: "20/08 → 30/08/2026", ar: "20/08 → 30/08/2026" },
      { fr: "21/08 → 31/08/2026", ar: "21/08 → 31/08/2026" },
    ],
    highlights: [
      { fr: "7 nuits en All Inclusive dans un resort 5* d'Antalya", ar: "7 ليالٍ بنظام الشامل في منتجع 5 نجوم بأنطاليا" },
      { fr: "Croisière sur le Bosphore incluse", ar: "رحلة بحرية في البوسفور مشمولة" },
      { fr: "Vol intérieur Istanbul – Antalya inclus", ar: "رحلة داخلية إسطنبول – أنطاليا مشمولة" },
      { fr: "Cascades de Düden et vieille ville de Kaleiçi", ar: "شلّالات دودن ومدينة كاليتشي العتيقة" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Casablanca – Istanbul", ar: "الدار البيضاء – إسطنبول" }, detail: { fr: "Arrivée à Istanbul, transfert et installation à l'hôtel. Temps libre autour de l'hôtel.", ar: "الوصول إلى إسطنبول، النقل والاستقرار بالفندق. وقت حرّ في محيط الفندق." } },
      { day: 2, title: { fr: "Istanbul – journée libre", ar: "إسطنبول – يوم حرّ" }, detail: { fr: "Mosquée Bleue, Sainte-Sophie, Grand Bazar ou cafés du quartier, à votre rythme.", ar: "المسجد الأزرق، آيا صوفيا، البازار الكبير أو مقاهي الحيّ، على إيقاعك." } },
      { day: 3, title: { fr: "Croisière sur le Bosphore", ar: "رحلة بحرية في البوسفور" }, detail: { fr: "Excursion en bateau devant les palais, ponts et quartiers historiques, puis place Taksim et avenue Istiklal.", ar: "جولة بحرية أمام القصور والجسور والأحياء التاريخية، ثم ساحة تقسيم وشارع الاستقلال." } },
      { day: 4, title: { fr: "Istanbul – Antalya", ar: "إسطنبول – أنطاليا" }, detail: { fr: "Vol intérieur vers Antalya, installation à l'hôtel puis temps libre à la marina ou en centre-ville.", ar: "رحلة داخلية نحو أنطاليا، الاستقرار بالفندق ثم وقت حرّ في المارينا أو وسط المدينة." } },
      { day: 5, title: { fr: "Antalya – journée libre", ar: "أنطاليا – يوم حرّ" }, detail: { fr: "Plages, marchés locaux, vieille ville de Kaleiçi et cafés typiques.", ar: "شواطئ وأسواق محلّية ومدينة كاليتشي العتيقة ومقاهٍ تقليدية." } },
      { day: 6, title: { fr: "Antalya – temps libre", ar: "أنطاليا – وقت حرّ" }, detail: { fr: "Mer, piscine ou découverte du port et des ruines antiques des environs.", ar: "البحر أو المسبح أو اكتشاف الميناء والأطلال القديمة المجاورة." } },
      { day: 7, title: { fr: "Antalya – temps libre", ar: "أنطاليا – وقت حرّ" }, detail: { fr: "Journée All Inclusive au resort ou excursion aux cascades de Düden.", ar: "يوم بنظام الشامل في المنتجع أو رحلة إلى شلّالات دودن." } },
      { day: 8, title: { fr: "Antalya – temps libre", ar: "أنطاليا – وقت حرّ" }, detail: { fr: "Détente en bord de mer et découverte des environs à votre rythme.", ar: "استرخاء على شاطئ البحر واكتشاف المحيط على إيقاعك." } },
      { day: 9, title: { fr: "Antalya – temps libre", ar: "أنطاليا – وقت حرّ" }, detail: { fr: "Plage, piscine ou shopping au centre commercial Mark Antalya.", ar: "الشاطئ أو المسبح أو التسوّق في مركز مارك أنطاليا." } },
      { day: 10, title: { fr: "Antalya – temps libre", ar: "أنطاليا – وقت حرّ" }, detail: { fr: "Dernière journée libre pour profiter du resort et de la Méditerranée.", ar: "آخر يوم حرّ للاستمتاع بالمنتجع والبحر الأبيض المتوسط." } },
      { day: 11, title: { fr: "Antalya – Istanbul – Casablanca", ar: "أنطاليا – إسطنبول – الدار البيضاء" }, detail: { fr: "Transfert à l'aéroport pour le vol retour vers Casablanca via Istanbul.", ar: "النقل إلى المطار لرحلة العودة نحو الدار البيضاء عبر إسطنبول." } },
    ],
    hotels: [
      { city: { fr: "Istanbul", ar: "إسطنبول" }, name: "Ramada by Wyndham Pera 5* / Taksim Square 4*", nights: 3 },
      { city: { fr: "Antalya", ar: "أنطاليا" }, name: "Kemer Ring Beach Resort 5*", nights: 7 },
      { city: { fr: "Antalya", ar: "أنطاليا" }, name: "Asteria Kremlin Palace 5*", nights: 7 },
      { city: { fr: "Antalya", ar: "أنطاليا" }, name: "Sirene Belek Resort 5* (chambre vue mer)", nights: 7 },
      { city: { fr: "Antalya", ar: "أنطاليا" }, name: "Swandor Topkapi Palace 5*", nights: 7 },
    ],
    pricing: [
      { label: { fr: "Kemer Ring Beach Resort 5* · Triple (à partir de)", ar: "كيمر رينغ 5* · ثلاثية (ابتداءً من)" }, mad: 19750 },
      { label: { fr: "Kemer Ring Beach Resort 5* · Double (à partir de)", ar: "كيمر رينغ 5* · مزدوجة (ابتداءً من)" }, mad: 20700 },
      { label: { fr: "Asteria Kremlin Palace 5* · Triple (à partir de)", ar: "أستيريا كرملين بالاس 5* · ثلاثية (ابتداءً من)" }, mad: 23500 },
      { label: { fr: "Asteria Kremlin Palace 5* · Double (à partir de)", ar: "أستيريا كرملين بالاس 5* · مزدوجة (ابتداءً من)" }, mad: 24500 },
      { label: { fr: "Swandor Topkapi Palace 5* · Triple (à partir de)", ar: "سواندور طوب قابي بالاس 5* · ثلاثية (ابتداءً من)" }, mad: 24400 },
      { label: { fr: "Sirene Belek Resort 5* vue mer · Triple (à partir de)", ar: "سيرين بيليك 5* إطلالة بحرية · ثلاثية (ابتداءً من)" }, mad: 24450 },
      { label: { fr: "Sirene Belek Resort 5* vue mer · Double (à partir de)", ar: "سيرين بيليك 5* إطلالة بحرية · مزدوجة (ابتداءً من)" }, mad: 25300 },
      { label: { fr: "Supplément single (selon l'hôtel, à partir de)", ar: "زيادة الغرفة الفردية (حسب الفندق، ابتداءً من)" }, mad: 8500 },
      { label: { fr: "Enfant de moins de 2 ans", ar: "طفل أقل من سنتين" }, mad: 800 },
      { label: { fr: "Enfant de 2 à 6 ans", ar: "طفل من 2 إلى 6 سنوات" }, mad: 8600 },
      { label: { fr: "Enfant de 7 à 11 ans (à partir de)", ar: "طفل من 7 إلى 11 سنة (ابتداءً من)" }, mad: 10300 },
    ],
    included: [
      { fr: "Vol Turkish Airlines en classe économique", ar: "رحلة مع الخطوط التركية في الدرجة السياحية" },
      { fr: "3 nuits à Istanbul avec petit déjeuner", ar: "3 ليالٍ في إسطنبول مع الفطور" },
      { fr: "7 nuits à Antalya en All Inclusive", ar: "7 ليالٍ في أنطاليا بنظام الشامل" },
      { fr: "Croisière sur le Bosphore", ar: "رحلة بحرية في البوسفور" },
      { fr: "Assistance et transferts aéroport / hôtel / aéroport", ar: "المرافقة والتنقّلات مطار / فندق / مطار" },
    ],
    notIncluded: [EXTRAS_NON_INCLUS],
    flights: [
      { route: { fr: "Casablanca → Istanbul", ar: "الدار البيضاء ← إسطنبول" }, time: "16h50 – 23h30" },
      { route: { fr: "Istanbul → Antalya", ar: "إسطنبول ← أنطاليا" }, time: "07h30 – 09h10" },
      { route: { fr: "Antalya → Istanbul", ar: "أنطاليا ← إسطنبول" }, time: "11h35 – 13h00" },
      { route: { fr: "Istanbul → Casablanca", ar: "إسطنبول ← الدار البيضاء" }, time: "12h05 – 14h55" },
    ],
  },

  {
    id: "istanbul-marmaris-bodrum-2026",
    slug: "istanbul-marmaris-bodrum-ete-2026",
    zone: TURQUIE,
    kind: "sejour",
    title: { fr: "Istanbul, Marmaris & Bodrum", ar: "إسطنبول ومرماريس وبودروم" },
    summary: {
      fr: "Istanbul puis la côte égéenne : Marmaris et Bodrum en All Inclusive, marinas, plages et vieilles villes.",
      ar: "إسطنبول ثم ساحل بحر إيجة: مرماريس وبودروم بنظام الشامل، مارينا وشواطئ ومدن عتيقة.",
    },
    region: { fr: "Istanbul & côte égéenne", ar: "إسطنبول وساحل إيجة" },
    days: 11,
    nights: 10,
    priceMad: 22900,
    image: "/media/tours/bodrum.webp",
    level: { fr: "Séjour balnéaire", ar: "إقامة شاطئية" },
    best: { fr: "Août 2026", ar: "غشت 2026" },
    flightIncluded: true,
    airline: "Turkish Airlines",
    departureCity: CASABLANCA,
    departures: [
      { fr: "31/07 → 10/08/2026", ar: "31/07 → 10/08/2026" },
      { fr: "03/08 → 13/08/2026", ar: "03/08 → 13/08/2026" },
      { fr: "04/08 → 14/08/2026", ar: "04/08 → 14/08/2026" },
      { fr: "09/08 → 19/08/2026", ar: "09/08 → 19/08/2026" },
      { fr: "10/08 → 20/08/2026", ar: "10/08 → 20/08/2026" },
      { fr: "16/08 → 26/08/2026", ar: "16/08 → 26/08/2026" },
      { fr: "17/08 → 27/08/2026", ar: "17/08 → 27/08/2026" },
      { fr: "21/08 → 31/08/2026", ar: "21/08 → 31/08/2026" },
    ],
    highlights: [
      { fr: "3 nuits à Marmaris et 4 nuits à Bodrum en All Inclusive", ar: "3 ليالٍ في مرماريس و4 في بودروم بنظام الشامل" },
      { fr: "Chambres vue mer dans les resorts balnéaires", ar: "غرف بإطلالة بحرية في المنتجعات الشاطئية" },
      { fr: "Croisière sur le Bosphore incluse", ar: "رحلة بحرية في البوسفور مشمولة" },
      { fr: "Château de Bodrum et marina de Marmaris", ar: "قلعة بودروم ومارينا مرماريس" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Casablanca – Istanbul", ar: "الدار البيضاء – إسطنبول" }, detail: { fr: "Arrivée, transfert et installation à l'hôtel. Première promenade dans le quartier.", ar: "الوصول والنقل والاستقرار بالفندق. أول نزهة في الحيّ." } },
      { day: 2, title: { fr: "Istanbul – journée libre", ar: "إسطنبول – يوم حرّ" }, detail: { fr: "Mosquée Bleue, Sainte-Sophie, Grand Bazar ou flânerie dans les rues animées.", ar: "المسجد الأزرق، آيا صوفيا، البازار الكبير أو تجوّل في الشوارع النابضة." } },
      { day: 3, title: { fr: "Croisière sur le Bosphore", ar: "رحلة بحرية في البوسفور" }, detail: { fr: "Palais, ponts et quartiers historiques vus du bateau, puis Taksim et Istiklal.", ar: "القصور والجسور والأحياء التاريخية من الباخرة، ثم تقسيم والاستقلال." } },
      { day: 4, title: { fr: "Istanbul – Marmaris", ar: "إسطنبول – مرماريس" }, detail: { fr: "Vol vers Dalaman puis route jusqu'à Marmaris. Temps libre à la marina et en bord de mer.", ar: "رحلة نحو دالامان ثم الطريق إلى مرماريس. وقت حرّ في المارينا وعلى الشاطئ." } },
      { day: 5, title: { fr: "Marmaris – temps libre", ar: "مرماريس – وقت حرّ" }, detail: { fr: "Plages, marchés locaux et vieille ville.", ar: "شواطئ وأسواق محلّية والمدينة العتيقة." } },
      { day: 6, title: { fr: "Marmaris – temps libre", ar: "مرماريس – وقت حرّ" }, detail: { fr: "Journée All Inclusive au resort ou promenade le long de la marina.", ar: "يوم بنظام الشامل في المنتجع أو نزهة على طول المارينا." } },
      { day: 7, title: { fr: "Marmaris – Bodrum", ar: "مرماريس – بودروم" }, detail: { fr: "Route vers Bodrum et installation à l'hôtel. Découverte de la marina et du centre-ville.", ar: "الطريق نحو بودروم والاستقرار بالفندق. اكتشاف المارينا ووسط المدينة." } },
      { day: 8, title: { fr: "Bodrum – temps libre", ar: "بودروم – وقت حرّ" }, detail: { fr: "Plages, château de Bodrum, marchés et cafés de la ville.", ar: "الشواطئ وقلعة بودروم وأسواق ومقاهي المدينة." } },
      { day: 9, title: { fr: "Bodrum – temps libre", ar: "بودروم – وقت حرّ" }, detail: { fr: "Détente au resort ou excursion en bateau dans les criques voisines.", ar: "استرخاء في المنتجع أو جولة بحرية في الخلجان المجاورة." } },
      { day: 10, title: { fr: "Bodrum – temps libre", ar: "بودروم – وقت حرّ" }, detail: { fr: "Dernière journée sur la côte égéenne.", ar: "آخر يوم على ساحل بحر إيجة." } },
      { day: 11, title: { fr: "Bodrum – Casablanca", ar: "بودروم – الدار البيضاء" }, detail: { fr: "Transfert à l'aéroport pour le vol retour via Istanbul.", ar: "النقل إلى المطار لرحلة العودة عبر إسطنبول." } },
    ],
    hotels: [
      { city: { fr: "Istanbul", ar: "إسطنبول" }, name: "Ramada by Wyndham Pera 5* / Taksim Square 4*", nights: 3 },
      { city: { fr: "Marmaris", ar: "مرماريس" }, name: "Green Nature Diamond Hotel", nights: 3 },
      { city: { fr: "Bodrum", ar: "بودروم" }, name: "Club Blue Dream Resort (chambre vue mer)", nights: 4 },
      { city: { fr: "Bodrum", ar: "بودروم" }, name: "La Blanche Islands (chambre vue mer)", nights: 4 },
    ],
    pricing: [
      { label: { fr: "Formule Club Blue Dream Resort · Triple (à partir de)", ar: "صيغة كلوب بلو دريم · ثلاثية (ابتداءً من)" }, mad: 22900 },
      { label: { fr: "Formule Club Blue Dream Resort · Double (à partir de)", ar: "صيغة كلوب بلو دريم · مزدوجة (ابتداءً من)" }, mad: 24250 },
      { label: { fr: "Formule Club Blue Dream Resort · Supplément single", ar: "صيغة كلوب بلو دريم · زيادة الغرفة الفردية" }, mad: 6850 },
      { label: { fr: "Formule La Blanche Islands · Triple (à partir de)", ar: "صيغة لا بلانش آيلاندز · ثلاثية (ابتداءً من)" }, mad: 26450 },
      { label: { fr: "Formule La Blanche Islands · Double (à partir de)", ar: "صيغة لا بلانش آيلاندز · مزدوجة (ابتداءً من)" }, mad: 28150 },
      { label: { fr: "Formule La Blanche Islands · Supplément single", ar: "صيغة لا بلانش آيلاندز · زيادة الغرفة الفردية" }, mad: 14650 },
      { label: { fr: "Enfant de moins de 2 ans", ar: "طفل أقل من سنتين" }, mad: 800 },
      { label: { fr: "Enfant de 2 à 6 ans", ar: "طفل من 2 إلى 6 سنوات" }, mad: 8400 },
      { label: { fr: "Enfant de 7 à 11 ans (à partir de)", ar: "طفل من 7 إلى 11 سنة (ابتداءً من)" }, mad: 10450 },
    ],
    included: [
      { fr: "Vol Turkish Airlines en classe économique", ar: "رحلة مع الخطوط التركية في الدرجة السياحية" },
      { fr: "3 nuits à Istanbul avec petit déjeuner", ar: "3 ليالٍ في إسطنبول مع الفطور" },
      { fr: "3 nuits à Marmaris en All Inclusive", ar: "3 ليالٍ في مرماريس بنظام الشامل" },
      { fr: "4 nuits à Bodrum en All Inclusive", ar: "4 ليالٍ في بودروم بنظام الشامل" },
      { fr: "Croisière sur le Bosphore", ar: "رحلة بحرية في البوسفور" },
      { fr: "Assistance et transferts aéroport / hôtel / aéroport", ar: "المرافقة والتنقّلات مطار / فندق / مطار" },
    ],
    notIncluded: [EXTRAS_NON_INCLUS],
    flights: [
      { route: { fr: "Casablanca → Istanbul", ar: "الدار البيضاء ← إسطنبول" }, time: "16h50 – 23h30" },
      { route: { fr: "Istanbul → Dalaman", ar: "إسطنبول ← دالامان" }, time: "12h30 – 13h50" },
      { route: { fr: "Bodrum → Istanbul", ar: "بودروم ← إسطنبول" }, time: "07h35 – 09h05" },
      { route: { fr: "Istanbul → Casablanca", ar: "إسطنبول ← الدار البيضاء" }, time: "12h05 – 14h55" },
    ],
  },

  {
    id: "turquie-anatolie",
    slug: "turquie-anatolie",
    zone: TURQUIE,
    kind: "circuit",
    title: { fr: "Anatolie — la grande traversée", ar: "الأناضول — العبور الكبير" },
    summary: {
      fr: "Cappadoce, Konya, Antalya, Fethiye, Pamukkale et Istanbul : treize nuits de circuit guidé, quatre croisières et des paysages classés à l'UNESCO.",
      ar: "كابادوكيا وقونية وأنطاليا وفتحية وباموكالي وإسطنبول: ثلاث عشرة ليلة من جولة مرشدة، أربع رحلات بحرية ومناظر مصنّفة لدى اليونسكو.",
    },
    region: { fr: "Cappadoce · Méditerranée · Istanbul", ar: "كابادوكيا · المتوسّط · إسطنبول" },
    days: 14,
    nights: 13,
    priceMad: 24700,
    image: "/media/tours/anatolie.webp",
    level: { fr: "Circuit guidé", ar: "جولة مرشدة" },
    best: { fr: "Juillet – Septembre 2026", ar: "يوليوز – شتنبر 2026" },
    flightIncluded: false,
    departureCity: CASABLANCA,
    departures: [
      { fr: "07/07 → 20/07/2026", ar: "07/07 → 20/07/2026" },
      { fr: "07/08 → 20/08/2026", ar: "07/08 → 20/08/2026" },
      { fr: "14/08 → 27/08/2026", ar: "14/08 → 27/08/2026" },
      { fr: "18/08 → 31/08/2026", ar: "18/08 → 31/08/2026" },
      { fr: "24/08 → 06/09/2026", ar: "24/08 → 06/09/2026" },
    ],
    highlights: [
      { fr: "Cheminées de fées et villes souterraines de Cappadoce", ar: "مداخن الجنّ والمدن الجوفية في كابادوكيا" },
      { fr: "4 croisières : Suluada, Ölüdeniz, Azmak et Bosphore", ar: "4 رحلات بحرية: سولوأدا، أولودينيز، أزماك والبوسفور" },
      { fr: "Pamukkale, le « château de coton » classé UNESCO", ar: "باموكالي، «قلعة القطن» المصنّفة لدى اليونسكو" },
      { fr: "Mausolée de Mevlana à Konya et canyon de Saklıkent", ar: "ضريح مولانا في قونية ووادي ساكليكنت" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Casablanca – Kayseri", ar: "الدار البيضاء – قيصري" }, detail: { fr: "Envol via Istanbul, accueil à Kayseri et transfert vers l'hôtel en Cappadoce.", ar: "الإقلاع عبر إسطنبول، الاستقبال في قيصري والنقل إلى الفندق بكابادوكيا." } },
      { day: 2, title: { fr: "Cappadoce", ar: "كابادوكيا" }, detail: { fr: "Village d'Uçhisar, vallée d'Avcılar avec vue sur Göreme, vallée de l'Imagination (Devrent) et vallée des Pigeonniers. Dîner et nuit.", ar: "قرية أوتشيصار، وادي أفجيلار بإطلالة على غوريمه، وادي الخيال (ديفرنت) ووادي أبراج الحمام. عشاء ومبيت." } },
      { day: 3, title: { fr: "Cappadoce – Konya", ar: "كابادوكيا – قونية" }, detail: { fr: "Vol en montgolfière en option, ville souterraine, village troglodytique d'Ortahisar et temps libre à Avanos. Route de la Soie et caravansérail vers Konya.", ar: "رحلة منطاد اختيارية، مدينة جوفية، قرية أورتاحيصار الصخرية ووقت حرّ في أفانوس. طريق الحرير وخان على الطريق إلى قونية." } },
      { day: 4, title: { fr: "Konya – Antalya", ar: "قونية – أنطاليا" }, detail: { fr: "Mausolée de Mevlana Jalal ad-Din Rumi, mosquée Aziziye et bazar Bedestan. Route vers Antalya, dîner et nuit.", ar: "ضريح مولانا جلال الدين الرومي، جامع العزيزية وسوق البدستان. الطريق نحو أنطاليا، عشاء ومبيت." } },
      { day: 5, title: { fr: "Antalya – visite de la ville", ar: "أنطاليا – زيارة المدينة" }, detail: { fr: "Vieux port et vieille ville de Kaleiçi, centre commercial Mark Antalya, puis cascade de Düden.", ar: "الميناء القديم ومدينة كاليتشي العتيقة، مركز مارك أنطاليا، ثم شلّال دودن." } },
      { day: 6, title: { fr: "Croisière à Suluada", ar: "رحلة بحرية إلى سولوأدا" }, detail: { fr: "Départ de la baie d'Adrasan vers l'île de Suluada, « les Maldives turques ». Déjeuner à bord et trois pauses baignade.", ar: "الانطلاق من خليج أدراسان نحو جزيرة سولوأدا، «مالديف تركيا». غداء على متن القارب وثلاث استراحات سباحة." } },
      { day: 7, title: { fr: "Antalya – Fethiye (canyon de Saklıkent)", ar: "أنطاليا – فتحية (وادي ساكليكنت)" }, detail: { fr: "Traversée du parc national de Saklıkent, l'un des canyons les plus profonds du monde. Déjeuner les pieds dans l'eau. Dîner et nuit à Fethiye.", ar: "عبور منتزه ساكليكنت الوطني، أحد أعمق الأودية في العالم. غداء والأقدام في الماء. عشاء ومبيت في فتحية." } },
      { day: 8, title: { fr: "Croisière à Ölüdeniz", ar: "رحلة بحرية إلى أولودينيز" }, detail: { fr: "Lagon bleu, plage des Papillons et île de Saint-Nicolas. Déjeuner grillades à bord, puis grotte Bleue et Source Froide.", ar: "البحيرة الزرقاء، شاطئ الفراشات وجزيرة القدّيس نيكولاس. غداء مشويّ على المتن، ثم الكهف الأزرق والنبع البارد." } },
      { day: 9, title: { fr: "Fethiye – Pamukkale", ar: "فتحية – باموكالي" }, detail: { fr: "Croisière sur le fleuve Azmak à Akyaka, arrêt panoramique sur la baie de Marmaris, puis route vers Pamukkale. Dîner et nuit à l'hôtel thermal.", ar: "رحلة على نهر أزماك في أكياكا، توقّف بانورامي على خليج مرماريس، ثم الطريق إلى باموكالي. عشاء ومبيت في الفندق الحراري." } },
      { day: 10, title: { fr: "Pamukkale", ar: "باموكالي" }, detail: { fr: "Cité antique de Hiérapolis et son théâtre romain, puis marche dans les bassins de calcaire blanc et les sources chaudes.", ar: "مدينة هيرابوليس الأثرية ومسرحها الروماني، ثم المشي في أحواض الكلس البيضاء والينابيع الحارّة." } },
      { day: 11, title: { fr: "Pamukkale – Istanbul", ar: "باموكالي – إسطنبول" }, detail: { fr: "Vol de Denizli vers Istanbul, transfert et installation à l'hôtel.", ar: "رحلة من دنيزلي نحو إسطنبول، النقل والاستقرار بالفندق." } },
      { day: 12, title: { fr: "Istanbul", ar: "إسطنبول" }, detail: { fr: "Croisière sur le Bosphore, marché égyptien, quartier d'Ortaköy et temps libre au Venezia Mall.", ar: "رحلة بحرية في البوسفور، السوق المصري، حيّ أورتاكوي ووقت حرّ في فينيزيا مول." } },
      { day: 13, title: { fr: "Istanbul – journée libre", ar: "إسطنبول – يوم حرّ" }, detail: { fr: "Journée libre pour les sites emblématiques, le shopping ou simplement se détendre.", ar: "يوم حرّ للمعالم البارزة أو التسوّق أو الاسترخاء." } },
      { day: 14, title: { fr: "Istanbul – Casablanca", ar: "إسطنبول – الدار البيضاء" }, detail: { fr: "Transfert à l'aéroport pour le vol retour.", ar: "النقل إلى المطار لرحلة العودة." } },
    ],
    hotels: [
      { city: { fr: "Cappadoce", ar: "كابادوكيا" }, name: "Zem Hotel Cappadocia 4*", nights: 2 },
      { city: { fr: "Konya", ar: "قونية" }, name: "Bayir Diamond 5*", nights: 1 },
      { city: { fr: "Antalya", ar: "أنطاليا" }, name: "Holiday Inn 5*", nights: 3 },
      { city: { fr: "Fethiye", ar: "فتحية" }, name: "Ata Park Hotel 4*", nights: 2 },
      { city: { fr: "Pamukkale", ar: "باموكالي" }, name: "Colossae Termal 5*", nights: 2 },
      { city: { fr: "Istanbul", ar: "إسطنبول" }, name: "Ramada Plaza by Wyndham 5*", nights: 3 },
    ],
    pricing: [
      { label: { fr: "Départs de juillet · Triple", ar: "رحلات يوليوز · ثلاثية" }, mad: 24700 },
      { label: { fr: "Départs de juillet · Double", ar: "رحلات يوليوز · مزدوجة" }, mad: 25300 },
      { label: { fr: "Départs de juillet · Supplément single", ar: "رحلات يوليوز · زيادة الغرفة الفردية" }, mad: 6700 },
      { label: { fr: "Départs d'août · Triple", ar: "رحلات غشت · ثلاثية" }, mad: 25700 },
      { label: { fr: "Départs d'août · Double", ar: "رحلات غشت · مزدوجة" }, mad: 26300 },
      { label: { fr: "Départs d'août · Supplément single", ar: "رحلات غشت · زيادة الغرفة الفردية" }, mad: 7700 },
    ],
    included: [
      { fr: "13 nuits d'hôtel en demi-pension, sauf Istanbul en petit déjeuner", ar: "13 ليلة فندقية بنصف إقامة، ما عدا إسطنبول بالفطور فقط" },
      { fr: "Guide professionnel francophone tout au long du circuit", ar: "مرشد محترف ناطق بالفرنسية طوال الجولة" },
      { fr: "Bus tout confort et climatisé, tous les transferts", ar: "حافلة مكيّفة ومريحة وجميع التنقّلات" },
      { fr: "Les entrées aux sites du programme", ar: "تذاكر الدخول إلى مواقع البرنامج" },
      { fr: "4 croisières (Suluada, Ölüdeniz, Azmak, Bosphore), dont 2 avec déjeuner", ar: "4 رحلات بحرية (سولوأدا، أولودينيز، أزماك، البوسفور)، منها اثنتان مع الغداء" },
    ],
    notIncluded: [
      { fr: "Les vols", ar: "تذاكر الطيران" },
      { fr: "Les déjeuners non mentionnés", ar: "الوجبات الغدائية غير المذكورة" },
      { fr: "Les boissons", ar: "المشروبات" },
    ],
    flights: [
      { route: { fr: "Casablanca → Istanbul", ar: "الدار البيضاء ← إسطنبول" }, time: "16h50 – 23h30" },
      { route: { fr: "Istanbul → Kayseri", ar: "إسطنبول ← قيصري" }, time: "01h50 – 03h15" },
      { route: { fr: "Denizli → Istanbul", ar: "دنيزلي ← إسطنبول" }, time: "13h15 – 14h30" },
      { route: { fr: "Istanbul → Casablanca", ar: "إسطنبول ← الدار البيضاء" }, time: "12h05 – 14h55" },
    ],
  },

  /* ====================================================================== */
  /*  ÉGYPTE                                                                */
  /* ====================================================================== */
  {
    id: "egypte-2026",
    slug: "egypte-nil-hurghada",
    zone: EGYPTE,
    kind: "circuit",
    title: { fr: "Égypte — du Caire au Nil, puis Hurghada", ar: "مصر — من القاهرة إلى النيل، ثم الغردقة" },
    summary: {
      fr: "Pyramides, train de nuit vers Assouan, croisière de trois nuits sur le Nil jusqu'à Louxor, puis cinq nuits en All Inclusive sur la mer Rouge.",
      ar: "الأهرامات، قطار ليلي نحو أسوان، رحلة نيلية لثلاث ليالٍ حتى الأقصر، ثم خمس ليالٍ بنظام الشامل على البحر الأحمر.",
    },
    region: { fr: "Le Caire · Nil · Mer Rouge", ar: "القاهرة · النيل · البحر الأحمر" },
    days: 15,
    nights: 14,
    priceMad: 23700,
    image: "/media/tours/egypte.webp",
    level: { fr: "Circuit & croisière", ar: "جولة ورحلة نيلية" },
    best: { fr: "13 → 27 août 2026", ar: "13 ← 27 غشت 2026" },
    flightIncluded: true,
    airline: "Royal Air Maroc",
    departureCity: CASABLANCA,
    departures: [{ fr: "13/08 → 27/08/2026", ar: "13/08 → 27/08/2026" }],
    highlights: [
      { fr: "Pyramides de Gizeh et Sphinx", ar: "أهرامات الجيزة وأبو الهول" },
      { fr: "Croisière sur le Nil en pension complète", ar: "رحلة نيلية بإقامة كاملة" },
      { fr: "Vallée des Rois et temple de Karnak à Louxor", ar: "وادي الملوك ومعبد الكرنك بالأقصر" },
      { fr: "5 nuits en All Inclusive à Hurghada", ar: "5 ليالٍ بنظام الشامل في الغردقة" },
      { fr: "Excursion à Alexandrie", ar: "رحلة إلى الإسكندرية" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Casablanca – Le Caire", ar: "الدار البيضاء – القاهرة" }, detail: { fr: "Vol direct depuis Casablanca, arrivée au Caire à 19h20, accueil et transfert à l'hôtel.", ar: "رحلة مباشرة من الدار البيضاء، الوصول إلى القاهرة على الساعة 19:20، الاستقبال والنقل إلى الفندق." } },
      { day: 2, title: { fr: "Gizeh & Le Caire", ar: "الجيزة والقاهرة" }, detail: { fr: "Pyramides et Sphinx de Gizeh, institut du papyrus, fabrique de parfum, Al-Azhar et Al-Hussein.", ar: "أهرامات وأبو الهول بالجيزة، معهد البردي، مصنع العطور، الأزهر والحسين." } },
      { day: 3, title: { fr: "Citadelle & musée égyptien", ar: "القلعة والمتحف المصري" }, detail: { fr: "Citadelle de Salah ad-Din al-Ayyoubi puis musée égyptien.", ar: "قلعة صلاح الدين الأيوبي ثم المتحف المصري." } },
      { day: 4, title: { fr: "Le Caire – Assouan (train de nuit)", ar: "القاهرة – أسوان (قطار ليلي)" }, detail: { fr: "Matinée libre, puis train couchette vers Assouan. Dîner et nuit à bord du train.", ar: "صباح حرّ، ثم قطار النوم نحو أسوان. عشاء ومبيت في القطار." } },
      { day: 5, title: { fr: "Assouan & embarquement", ar: "أسوان والصعود إلى الباخرة" }, detail: { fr: "Haut barrage et obélisque inachevé, jardin botanique et musée de Nubie. Embarquement à 13h00, déjeuner à bord.", ar: "السدّ العالي والمسلّة الناقصة، الحديقة النباتية ومتحف النوبة. الصعود على الساعة 13:00 وغداء على المتن." } },
      { day: 6, title: { fr: "Kom Ombo – Edfou – Louxor", ar: "كوم أمبو – إدفو – الأقصر" }, detail: { fr: "Temple de Kom Ombo dédié à Sobek et Horus, temple d'Edfou, puis navigation jusqu'à Louxor.", ar: "معبد كوم أمبو المكرّس لسوبك وحورس، معبد إدفو، ثم الإبحار إلى الأقصر." } },
      { day: 7, title: { fr: "Louxor", ar: "الأقصر" }, detail: { fr: "Vallée des Rois et tombeau de Toutânkhamon, colosses de Memnon, temples de Karnak, Louxor et Hatchepsout.", ar: "وادي الملوك ومقبرة توت عنخ آمون، تمثالا ممنون، معابد الكرنك والأقصر وحتشبسوت." } },
      { day: 8, title: { fr: "Louxor – Hurghada", ar: "الأقصر – الغردقة" }, detail: { fr: "Route en bus climatisé vers Hurghada et installation à l'hôtel.", ar: "الطريق بحافلة مكيّفة نحو الغردقة والاستقرار بالفندق." } },
      { day: 9, title: { fr: "Hurghada", ar: "الغردقة" }, detail: { fr: "Journée libre en All Inclusive.", ar: "يوم حرّ بنظام الشامل." } },
      { day: 10, title: { fr: "Hurghada", ar: "الغردقة" }, detail: { fr: "Journée libre en All Inclusive.", ar: "يوم حرّ بنظام الشامل." } },
      { day: 11, title: { fr: "Hurghada", ar: "الغردقة" }, detail: { fr: "Journée libre en All Inclusive.", ar: "يوم حرّ بنظام الشامل." } },
      { day: 12, title: { fr: "Hurghada", ar: "الغردقة" }, detail: { fr: "Journée libre en All Inclusive.", ar: "يوم حرّ بنظام الشامل." } },
      { day: 13, title: { fr: "Hurghada – Le Caire", ar: "الغردقة – القاهرة" }, detail: { fr: "Route de retour vers Le Caire, assistance et transfert à l'hôtel.", ar: "طريق العودة نحو القاهرة، المساعدة والنقل إلى الفندق." } },
      { day: 14, title: { fr: "Excursion à Alexandrie", ar: "رحلة إلى الإسكندرية" }, detail: { fr: "Château de Qaitbay, mosquée d'Abu al-Abbas et jardins de Montazah. Retour au Caire.", ar: "قلعة قايتباي، مسجد أبو العباس وحدائق المنتزه. العودة إلى القاهرة." } },
      { day: 15, title: { fr: "Le Caire – Casablanca", ar: "القاهرة – الدار البيضاء" }, detail: { fr: "Transfert à l'aéroport pour le vol retour.", ar: "النقل إلى المطار لرحلة العودة." } },
    ],
    hotels: [
      { city: { fr: "Le Caire", ar: "القاهرة" }, name: "Holiday Inn City Stars 5*", nights: 5 },
      { city: { fr: "Le Caire → Assouan", ar: "القاهرة ← أسوان" }, name: "Train — cabine couchette", nights: 1 },
      { city: { fr: "Croisière sur le Nil", ar: "رحلة نيلية" }, name: "Bateau 5* en pension complète", nights: 3 },
      { city: { fr: "Hurghada", ar: "الغردقة" }, name: "Swiss Inn Resort 5*", nights: 5 },
    ],
    pricing: [
      { label: { fr: "Chambre triple", ar: "غرفة ثلاثية" }, mad: 23700 },
      { label: { fr: "Chambre double", ar: "غرفة مزدوجة" }, mad: 24700 },
      { label: { fr: "Supplément single", ar: "زيادة الغرفة الفردية" }, mad: 6700 },
    ],
    included: [
      { fr: "Vol direct Royal Air Maroc en classe économique", ar: "رحلة مباشرة مع الخطوط الملكية المغربية في الدرجة السياحية" },
      { fr: "Le Caire en petit déjeuner, train en demi-pension", ar: "القاهرة بالفطور، والقطار بنصف إقامة" },
      { fr: "Croisière sur le Nil en pension complète", ar: "الرحلة النيلية بإقامة كاملة" },
      { fr: "Hurghada en All Inclusive", ar: "الغردقة بنظام الشامل" },
      { fr: "Transferts, excursions et visites du programme", ar: "التنقّلات والرحلات والزيارات المذكورة في البرنامج" },
      { fr: "Guide accompagnateur arabophone pendant tout le voyage", ar: "مرشد مرافق ناطق بالعربية طوال الرحلة" },
    ],
    notIncluded: [
      { fr: "Frais de visa : 500 Dhs", ar: "رسوم التأشيرة: 500 درهم" },
      { fr: "Pourboires — prévoir 30 USD par personne pour le guide à l'arrivée (obligatoire)", ar: "الإكراميات — 30 دولارًا للشخص للمرشد عند الوصول (إلزامية)" },
      { fr: "Vols intérieurs en option : Le Caire → Assouan 1 300 Dhs, Hurghada → Le Caire 1 300 Dhs", ar: "رحلات داخلية اختيارية: القاهرة ← أسوان 1300 درهم، الغردقة ← القاهرة 1300 درهم" },
      { fr: "Les boissons", ar: "المشروبات" },
      EXTRAS_NON_INCLUS,
    ],
    flights: [
      { route: { fr: "Casablanca → Le Caire (13 août)", ar: "الدار البيضاء ← القاهرة (13 غشت)" }, time: "11h00 – 19h20" },
      { route: { fr: "Le Caire → Casablanca (27 août)", ar: "القاهرة ← الدار البيضاء (27 غشت)" }, time: "08h40 – 13h30" },
    ],
    visa: {
      fr: "Visa égyptien : 500 Dhs. Les titulaires d'un visa Schengen ou américain en cours de validité et déjà utilisé sont dispensés de visa. Pièces à fournir : passeport valable 6 mois après le retour, copie de la CNI, 2 photos 35 × 45 mm fond blanc, attestation de travail ou de scolarité, 3 derniers relevés bancaires cachetés, acte de mariage pour la prise en charge du conjoint.",
      ar: "التأشيرة المصرية: 500 درهم. حاملو تأشيرة شنغن أو أمريكية سارية ومستعملة سابقًا معفون منها. الوثائق المطلوبة: جواز سفر صالح 6 أشهر بعد العودة، نسخة من البطاقة الوطنية، صورتان 35×45 ملم بخلفية بيضاء، شهادة عمل أو مدرسية، آخر 3 كشوف بنكية مختومة، وعقد الزواج لتكفّل الزوج بزوجته.",
    },
  },

  /* ====================================================================== */
  /*  BALKANS                                                               */
  /* ====================================================================== */
  {
    id: "grand-tour-balkans",
    slug: "grand-tour-balkans",
    zone: BALKANS,
    kind: "circuit",
    title: { fr: "Grand Tour des Balkans", ar: "الجولة الكبرى في البلقان" },
    summary: {
      fr: "Bosnie, Croatie, Monténégro, Albanie et Corfou en quinze jours : Sarajevo, Mostar, Dubrovnik, Kotor, Butrint et Berat, avec 25 repas inclus.",
      ar: "البوسنة وكرواتيا والجبل الأسود وألبانيا وكورفو في خمسة عشر يومًا: سراييفو وموستار ودوبروفنيك وكوتور وبوترينت وبيرات، مع 25 وجبة مشمولة.",
    },
    region: { fr: "Bosnie · Croatie · Monténégro · Albanie · Grèce", ar: "البوسنة · كرواتيا · الجبل الأسود · ألبانيا · اليونان" },
    days: 15,
    nights: 14,
    priceMad: 31700,
    image: "/media/tours/balkans.webp",
    level: { fr: "Circuit guidé", ar: "جولة مرشدة" },
    best: { fr: "15 → 29 août 2026", ar: "15 ← 29 غشت 2026" },
    flightIncluded: true,
    airline: "Turkish Airlines",
    departureCity: CASABLANCA,
    departures: [{ fr: "15/08 → 29/08/2026", ar: "15/08 → 29/08/2026" }],
    highlights: [
      { fr: "Vieux Pont de Mostar et Tunnel de l'Espoir à Sarajevo", ar: "الجسر القديم بموستار ونفق الأمل بسراييفو" },
      { fr: "Remparts de Dubrovnik et baie de Kotor en bateau", ar: "أسوار دوبروفنيك وخليج كوتور بالقارب" },
      { fr: "Excursion en ferry vers Corfou et Paleokastritsa", ar: "رحلة بالعبّارة نحو كورفو وباليوكاستريتسا" },
      { fr: "Butrint et Berat, deux sites classés UNESCO", ar: "بوترينت وبيرات، موقعان مصنّفان لدى اليونسكو" },
      { fr: "Dîner de clôture avec musique folklorique live à Tirana", ar: "عشاء ختامي مع موسيقى فولكلورية حيّة في تيرانا" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Casablanca – Istanbul", ar: "الدار البيضاء – إسطنبول" }, detail: { fr: "Départ de Casablanca. Nuit d'escale à Istanbul prise en charge par la compagnie aérienne.", ar: "الانطلاق من الدار البيضاء. ليلة التوقّف في إسطنبول على حساب شركة الطيران." } },
      { day: 2, title: { fr: "Istanbul – Sarajevo", ar: "إسطنبول – سراييفو" }, detail: { fr: "Arrivée à Sarajevo, accueil par le guide local, déjeuner puis transfert à l'hôtel.", ar: "الوصول إلى سراييفو، الاستقبال من المرشد المحلّي، غداء ثم النقل إلى الفندق." } },
      { day: 3, title: { fr: "Sarajevo", ar: "سراييفو" }, detail: { fr: "Mosquée Gazi Husrev-beg du XVIe siècle, cathédrale du Sacré-Cœur, puis Tunnel de l'Espoir. Dîner à l'hôtel.", ar: "جامع غازي خسرو بك من القرن السادس عشر، كاتدرائية القلب الأقدس، ثم نفق الأمل. عشاء بالفندق." } },
      { day: 4, title: { fr: "Sarajevo – Mostar", ar: "سراييفو – موستار" }, detail: { fr: "Vieux Pont ottoman sur la Neretva, maison Biščevića et mosquée Koski Mehmed Pacha. Dîner et nuit.", ar: "الجسر العثماني القديم على نهر نيريتفا، دار بيشتشيفيتش وجامع كوسكي محمد باشا. عشاء ومبيت." } },
      { day: 5, title: { fr: "Mostar – Dubrovnik", ar: "موستار – دوبروفنيك" }, detail: { fr: "Route panoramique le long de l'Adriatique, puis promenade sur les remparts de Dubrovnik. Dîner et nuit.", ar: "طريق بانورامي على طول الأدرياتيكي، ثم نزهة على أسوار دوبروفنيك. عشاء ومبيت." } },
      { day: 6, title: { fr: "Dubrovnik – Budva", ar: "دوبروفنيك – بودفا" }, detail: { fr: "Côte adriatique jusqu'à Budva, visite guidée de la vieille ville médiévale et promenade en bord de mer.", ar: "الساحل الأدرياتيكي حتى بودفا، زيارة مرشدة للمدينة القروسطية ونزهة على الشاطئ." } },
      { day: 7, title: { fr: "Budva – Kotor – Budva", ar: "بودفا – كوتور – بودفا" }, detail: { fr: "Vieille ville de Kotor, excursion en bateau dans la baie et visite de l'île de Notre-Dame-du-Rocher. Retour à Budva.", ar: "مدينة كوتور العتيقة، جولة بحرية في الخليج وزيارة جزيرة سيّدة الصخرة. العودة إلى بودفا." } },
      { day: 8, title: { fr: "Budva – Shkodër – Durrës", ar: "بودفا – شكودر – دوريس" }, detail: { fr: "Boulevard Kolë Idromeno à Shkodër et son architecture austro-hongroise, déjeuner local, puis route vers Durrës.", ar: "شارع كولّه إدروميّنو في شكودر وعمارته النمساوية المجرية، غداء محلّي، ثم الطريق نحو دوريس." } },
      { day: 9, title: { fr: "Durrës – Vlorë – Saranda", ar: "دوريس – فلورا – ساراندا" }, detail: { fr: "Amphithéâtre romain et tour vénitienne de Durrës, Vlorë berceau de l'indépendance, puis route panoramique sur la mer Ionienne.", ar: "المدرّج الروماني والبرج البندقي بدوريس، فلورا مهد الاستقلال، ثم طريق بانورامي على البحر الأيوني." } },
      { day: 10, title: { fr: "Butrint & Ksamil", ar: "بوترينت وكسميل" }, detail: { fr: "Parc national de Butrint classé UNESCO — théâtre antique, temples et murailles — puis pause déjeuner à Ksamil. Dîner à Saranda.", ar: "منتزه بوترينت الوطني المصنّف لدى اليونسكو — مسرح أثري ومعابد وأسوار — ثم استراحة غداء في كسميل. عشاء في ساراندا." } },
      { day: 11, title: { fr: "Excursion à Corfou", ar: "رحلة إلى كورفو" }, detail: { fr: "Ferry vers l'île grecque, baignade à Paleokastritsa, puis vieille ville UNESCO, Spianada, Liston et église Saint-Spyridon.", ar: "عبّارة نحو الجزيرة اليونانية، سباحة في باليوكاستريتسا، ثم المدينة العتيقة المصنّفة، سبيانادا وليستون وكنيسة القدّيس سبيريدون." } },
      { day: 12, title: { fr: "Saranda – Berat – Tirana", ar: "ساراندا – بيرات – تيرانا" }, detail: { fr: "Berat, « la ville aux mille fenêtres » : quartiers Mangalem et Gorica, citadelle habitée et musée Onufri. Route vers Tirana.", ar: "بيرات، «مدينة الألف نافذة»: حيّا منغاليم وغوريتسا، القلعة المأهولة ومتحف أونوفري. الطريق نحو تيرانا." } },
      { day: 13, title: { fr: "Tirana", ar: "تيرانا" }, detail: { fr: "Place Skanderbeg, musée Bunk'Art dans un bunker antiatomique et quartier Blloku. Dîner traditionnel avec musique folklorique live.", ar: "ساحة سكاندربيغ، متحف بونك آرت داخل ملجأ نووي وحيّ بلوكو. عشاء تقليدي مع موسيقى فولكلورية حيّة." } },
      { day: 14, title: { fr: "Tirana – Kruja – Istanbul", ar: "تيرانا – كرويا – إسطنبول" }, detail: { fr: "Château de Kruja, musée Skanderbeg et bazar traditionnel. Déjeuner local puis transfert à l'aéroport. Nuit d'escale à Istanbul.", ar: "قلعة كرويا ومتحف سكاندربيغ والسوق التقليدي. غداء محلّي ثم النقل إلى المطار. ليلة توقّف في إسطنبول." } },
      { day: 15, title: { fr: "Istanbul – Casablanca", ar: "إسطنبول – الدار البيضاء" }, detail: { fr: "Vol retour vers Casablanca. Fin de nos services.", ar: "رحلة العودة نحو الدار البيضاء. نهاية خدماتنا." } },
    ],
    hotels: [
      { city: { fr: "Istanbul (escale)", ar: "إسطنبول (توقّف)" }, name: "Hôtel aéroport 4*", nights: 2 },
      { city: { fr: "Sarajevo", ar: "سراييفو" }, name: "Mövenpick Hotel 5*", nights: 2 },
      { city: { fr: "Mostar", ar: "موستار" }, name: "Hotel Mepas 4*", nights: 1 },
      { city: { fr: "Dubrovnik", ar: "دوبروفنيك" }, name: "Grand Hotel Park 4*", nights: 1 },
      { city: { fr: "Budva", ar: "بودفا" }, name: "Hotel Bracera 5*", nights: 2 },
      { city: { fr: "Durrës", ar: "دوريس" }, name: "Hotel Arvi 5*", nights: 1 },
      { city: { fr: "Saranda", ar: "ساراندا" }, name: "Toer Hotel & Spa", nights: 3 },
      { city: { fr: "Tirana", ar: "تيرانا" }, name: "Hotel Mak Albania", nights: 2 },
    ],
    pricing: [
      { label: { fr: "Chambre triple", ar: "غرفة ثلاثية" }, mad: 31700 },
      { label: { fr: "Chambre double", ar: "غرفة مزدوجة" }, mad: 32200 },
      { label: { fr: "Supplément single", ar: "زيادة الغرفة الفردية" }, mad: 7700 },
    ],
    included: [
      { fr: "Vol direct Turkish Airlines en classe économique", ar: "رحلة مباشرة مع الخطوط التركية في الدرجة السياحية" },
      { fr: "12 nuits en hôtels 4* et 5*", ar: "12 ليلة في فنادق 4 و5 نجوم" },
      { fr: "25 repas (eau incluse), dont un dîner de clôture avec musique folklorique live", ar: "25 وجبة (الماء مشمول)، منها عشاء ختامي مع موسيقى فولكلورية حيّة" },
      { fr: "Autocar et guide francophone ou arabophone durant tout le circuit", ar: "حافلة ومرشد ناطق بالفرنسية أو العربية طوال الجولة" },
      { fr: "Guides locaux à Sarajevo, Mostar, Dubrovnik, Budva, Kotor et Corfou", ar: "مرشدون محلّيون في سراييفو وموستار ودوبروفنيك وبودفا وكوتور وكورفو" },
      { fr: "Ferry Saranda / Corfou / Saranda, excursion en bateau à Kotor et balade au parc national de Karavasta", ar: "عبّارة ساراندا / كورفو / ساراندا، جولة بحرية في كوتور ونزهة في منتزه كارافاستا الوطني" },
    ],
    notIncluded: [
      { fr: "Visa Schengen obligatoire — non pris en charge par l'agence", ar: "تأشيرة شنغن إلزامية — الوكالة لا تتكفّل بها" },
      { fr: "Les repas et boissons non mentionnés au programme", ar: "الوجبات والمشروبات غير المذكورة في البرنامج" },
      { fr: "Les pourboires aux chauffeurs et guides", ar: "إكراميات السائقين والمرشدين" },
      { fr: "L'assurance voyage et les dépenses personnelles", ar: "تأمين السفر والمصاريف الشخصية" },
    ],
    flights: [
      { route: { fr: "Casablanca → Istanbul (15 août)", ar: "الدار البيضاء ← إسطنبول (15 غشت)" }, time: "16h50 – 23h30" },
      { route: { fr: "Istanbul → Sarajevo (16 août)", ar: "إسطنبول ← سراييفو (16 غشت)" }, time: "12h45 – 13h35" },
      { route: { fr: "Tirana → Istanbul (28 août)", ar: "تيرانا ← إسطنبول (28 غشت)" }, time: "19h50 – 22h35" },
      { route: { fr: "Istanbul → Casablanca (29 août)", ar: "إسطنبول ← الدار البيضاء (29 غشت)" }, time: "12h05 – 14h55" },
    ],
    visa: {
      fr: "Visa Schengen obligatoire. L'agence ne prend pas en charge la constitution du dossier de visa pour ce circuit.",
      ar: "تأشيرة شنغن إلزامية. لا تتكفّل الوكالة بإعداد ملف التأشيرة لهذه الجولة.",
    },
  },

  /* ====================================================================== */
  /*  CHINE                                                                 */
  /* ====================================================================== */
  {
    id: "chine-2026",
    slug: "chine-grand-tour",
    zone: CHINE,
    kind: "circuit",
    title: { fr: "Chine — Pékin, Xi'an, Guilin & Shanghai", ar: "الصين — بكين وشيان وغويلين وشنغهاي" },
    summary: {
      fr: "Quinze jours de la Cité interdite à la rivière Li : Grande Muraille, guerriers en terre cuite, radeaux de Yangshuo et Shanghai futuriste.",
      ar: "خمسة عشر يومًا من المدينة المحرّمة إلى نهر لي: سور الصين العظيم، جيش الطين، أطواف يانغشو وشنغهاي المستقبلية.",
    },
    region: { fr: "Pékin · Xi'an · Guilin · Shanghai", ar: "بكين · شيان · غويلين · شنغهاي" },
    days: 15,
    nights: 12,
    priceMad: 39000,
    image: "/media/tours/chine.webp",
    level: { fr: "Grand circuit", ar: "جولة كبرى" },
    best: { fr: "10 → 24 août 2026", ar: "10 ← 24 غشت 2026" },
    flightIncluded: true,
    airline: "Royal Air Maroc",
    departureCity: CASABLANCA,
    departures: [{ fr: "10/08 → 24/08/2026", ar: "10/08 → 24/08/2026" }],
    highlights: [
      { fr: "Cité interdite, place Tian'anmen et Temple du Ciel", ar: "المدينة المحرّمة وساحة تيان آنمن ومعبد السماء" },
      { fr: "Trois heures sur la Grande Muraille à Juyongguan", ar: "ثلاث ساعات على سور الصين العظيم في جويونغقوان" },
      { fr: "Armée de 6 000 guerriers en terre cuite de Xi'an", ar: "جيش الستة آلاف محارب من الطين في شيان" },
      { fr: "Croisière en radeau sur la rivière Li", ar: "جولة بالطوف على نهر لي" },
      { fr: "Déjeuner chez l'habitant dans les hutongs de Pékin", ar: "غداء عند السكّان في هوتونغ بكين" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Casablanca – Pékin", ar: "الدار البيضاء – بكين" }, detail: { fr: "Rendez-vous à 12h30 à l'aéroport Mohammed V pour le vol direct vers Pékin.", ar: "الموعد على الساعة 12:30 بمطار محمد الخامس للرحلة المباشرة نحو بكين." } },
      { day: 2, title: { fr: "Arrivée à Pékin", ar: "الوصول إلى بكين" }, detail: { fr: "Accueil, transfert en ville et installation à l'hôtel. Dîner inclus.", ar: "الاستقبال والنقل إلى المدينة والاستقرار بالفندق. العشاء مشمول." } },
      { day: 3, title: { fr: "Pékin historique", ar: "بكين التاريخية" }, detail: { fr: "Place Tian'anmen, Cité interdite et ses 900 salles, déjeuner local puis Temple du Ciel.", ar: "ساحة تيان آنمن، المدينة المحرّمة بقاعاتها التسعمائة، غداء محلّي ثم معبد السماء." } },
      { day: 4, title: { fr: "Grande Muraille & Palais d'Été", ar: "سور الصين العظيم وقصر الصيف" }, detail: { fr: "Excursion à la Grande Muraille de Juyongguan (3 h sur le site), initiation au chinois, déjeuner local puis Palais d'Été.", ar: "رحلة إلى سور جويونغقوان (3 ساعات في الموقع)، مبادئ اللغة الصينية، غداء محلّي ثم قصر الصيف." } },
      { day: 5, title: { fr: "Pékin — parc olympique & hutongs", ar: "بكين — المنتزه الأولمبي والهوتونغ" }, detail: { fr: "Cube d'Eau et Nid d'Oiseau, initiation au taiji, déjeuner et atelier raviolis chez l'habitant, puis Temple des Lamas.", ar: "مكعّب الماء وعشّ الطائر، مبادئ التاي تشي، غداء وورشة الرافيولي عند السكّان، ثم معبد اللاما." } },
      { day: 6, title: { fr: "Pékin – Xi'an (TGV)", ar: "بكين – شيان (قطار سريع)" }, detail: { fr: "Train rapide (5 h) vers Xi'an, l'une des plus anciennes capitales de Chine. Vieux quartiers et Grande Mosquée.", ar: "قطار سريع (5 ساعات) نحو شيان، إحدى أقدم عواصم الصين. الأحياء القديمة والجامع الكبير." } },
      { day: 7, title: { fr: "Xi'an — guerriers en terre cuite", ar: "شيان — جيش الطين" }, detail: { fr: "Grande Pagode de l'Oie Sauvage, cours de calligraphie, fabrique de jade, puis les Grandes Fouilles du tombeau de Qin Shi Huang.", ar: "معبدة الإوزّة البرّية الكبرى، درس خطّ، مصنع اليشم، ثم حفريات ضريح تشين شي هوانغ." } },
      { day: 8, title: { fr: "Xi'an – Guilin – Yangshuo", ar: "شيان – غويلين – يانغشو" }, detail: { fr: "Vol vers Guilin, croisière en radeau entre Yangdi et Jiumahuashan sur la rivière Li, puis village millénaire de Xingping.", ar: "رحلة نحو غويلين، جولة بالطوف بين يانغدي وجيوماهواشان على نهر لي، ثم قرية شينغبينغ العريقة." } },
      { day: 9, title: { fr: "Yangshuo", ar: "يانغشو" }, detail: { fr: "Journée libre et temps libre au marché Ouest, entre échoppes, bars et restaurants.", ar: "يوم حرّ ووقت حرّ في السوق الغربي، بين الدكاكين والمقاهي والمطاعم." } },
      { day: 10, title: { fr: "Yangshuo – Guilin – Shanghai", ar: "يانغشو – غويلين – شنغهاي" }, detail: { fr: "Champs de théiers et dégustation, pagodes du Soleil et de la Lune, lac des Banians, puis vol vers Shanghai.", ar: "حقول الشاي وتذوّقه، معبدتا الشمس والقمر، بحيرة البانيان، ثم رحلة نحو شنغهاي." } },
      { day: 11, title: { fr: "Shanghai", ar: "شنغهاي" }, detail: { fr: "Le Bund, traversée de la Huangpu vers Pudong, vieux Shanghai et jardin Yu, puis ancienne concession française.", ar: "الباوند، عبور نهر هوانغبو نحو بودونغ، شنغهاي القديمة وحديقة يو، ثم الحيّ الفرنسي القديم." } },
      { day: 12, title: { fr: "Shanghai – Tongli – Suzhou", ar: "شنغهاي – تونغلي – سوجو" }, detail: { fr: "Village de Tongli et mini-croisière sur ses canaux, puis Suzhou : jardin du Maître des filets et quartier Shantangjie.", ar: "قرية تونغلي وجولة قصيرة على قنواتها، ثم سوجو: حديقة سيّد الشباك وحيّ شانتانغجيه." } },
      { day: 13, title: { fr: "Shanghai – Pékin (TGV)", ar: "شنغهاي – بكين (قطار سريع)" }, detail: { fr: "Journée libre, puis TGV en fin d'après-midi vers Pékin et transfert à l'hôtel.", ar: "يوم حرّ، ثم قطار سريع في نهاية بعد الظهر نحو بكين والنقل إلى الفندق." } },
      { day: 14, title: { fr: "Pékin – retour", ar: "بكين – العودة" }, detail: { fr: "Transfert à l'aéroport et vol de retour.", ar: "النقل إلى المطار ورحلة العودة." } },
      { day: 15, title: { fr: "Arrivée à Casablanca", ar: "الوصول إلى الدار البيضاء" }, detail: { fr: "Arrivée à Casablanca. Fin de nos services.", ar: "الوصول إلى الدار البيضاء. نهاية خدماتنا." } },
    ],
    hotels: [
      { city: { fr: "Pékin", ar: "بكين" }, name: "New Yunnan Crowne Plaza 5*", nights: 5 },
      { city: { fr: "Xi'an", ar: "شيان" }, name: "Grand Mercure 5*", nights: 2 },
      { city: { fr: "Yangshuo", ar: "يانغشو" }, name: "Greenlotus Hotel 5*", nights: 2 },
      { city: { fr: "Shanghai", ar: "شنغهاي" }, name: "The Yangtze Boutique Hotel 5*", nights: 3 },
    ],
    pricing: [
      { label: { fr: "Chambre triple", ar: "غرفة ثلاثية" }, mad: 39000 },
      { label: { fr: "Chambre double", ar: "غرفة مزدوجة" }, mad: 39500 },
      { label: { fr: "Supplément single", ar: "زيادة الغرفة الفردية" }, mad: 7800 },
    ],
    included: [
      { fr: "Vol direct Royal Air Maroc en classe économique", ar: "رحلة مباشرة مع الخطوط الملكية المغربية في الدرجة السياحية" },
      { fr: "12 nuits d'hôtel 5* avec petits déjeuners et les repas mentionnés", ar: "12 ليلة في فنادق 5 نجوم مع الفطور والوجبات المذكورة" },
      { fr: "2 trains rapides Pékin / Xi'an et Shanghai / Pékin en 2e classe", ar: "قطاران سريعان بكين / شيان وشنغهاي / بكين في الدرجة الثانية" },
      { fr: "Vols intérieurs Xi'an / Guilin et Guilin / Shanghai", ar: "رحلتان داخليتان شيان / غويلين وغويلين / شنغهاي" },
      { fr: "Guides locaux francophones et guide national accompagnateur", ar: "مرشدون محلّيون ناطقون بالفرنسية ومرشد وطني مرافق" },
      { fr: "Les transferts et les entrées des visites du programme", ar: "التنقّلات وتذاكر دخول زيارات البرنامج" },
    ],
    notIncluded: [
      { fr: "Frais de visa : 600 Dhs (disponible chez Tamesna Voyages)", ar: "رسوم التأشيرة: 600 درهم (متوفّرة لدى تامسنا فوياج)" },
      { fr: "Pourboires aux chauffeurs et guides : 5 USD par personne et par jour", ar: "إكراميات السائقين والمرشدين: 5 دولارات للشخص يوميًّا" },
      { fr: "Les repas et boissons non mentionnés au programme", ar: "الوجبات والمشروبات غير المذكورة في البرنامج" },
      { fr: "L'assurance voyage et les dépenses personnelles", ar: "تأمين السفر والمصاريف الشخصية" },
    ],
    options: [
      { label: { fr: "Soirée cirque à Pékin — sur demande", ar: "أمسية سيرك في بكين — عند الطلب" }, mad: 0 },
      { label: { fr: "Dîner de raviolis et spectacle Tang à Xi'an — sur demande", ar: "عشاء رافيولي وعرض تانغ في شيان — عند الطلب" }, mad: 0 },
      { label: { fr: "Spectacle « Impression de Liusanjie » à Yangshuo — sur demande", ar: "عرض «انطباع ليوسانجيه» في يانغشو — عند الطلب" }, mad: 0 },
    ],
    flights: [
      { route: { fr: "Casablanca → Pékin (10 août)", ar: "الدار البيضاء ← بكين (10 غشت)" }, time: "16h05 – 11h25 (+1)" },
      { route: { fr: "Pékin → Casablanca (23 août)", ar: "بكين ← الدار البيضاء (23 غشت)" }, time: "13h25 – 19h25" },
    ],
    visa: {
      fr: "Visa touristique chinois : 600 Dhs, disponible chez Tamesna Voyages. Pièces à fournir : formulaire signé avec photo 48 × 33 mm sur fond clair, passeport valable 6 mois avec trois pages vierges et photocopie A4, copies des anciens visas chinois, attestation de travail ou de pension, carte de séjour pour les non-Marocains, attestation d'assurance et dernier relevé bancaire cacheté de 30 000 Dhs minimum.",
      ar: "التأشيرة السياحية الصينية: 600 درهم، متوفّرة لدى تامسنا فوياج. الوثائق المطلوبة: استمارة موقّعة مع صورة 48×33 ملم بخلفية فاتحة، جواز سفر صالح 6 أشهر بثلاث صفحات فارغة ونسخة A4، نسخ من التأشيرات الصينية السابقة، شهادة عمل أو معاش، بطاقة الإقامة لغير المغاربة، شهادة تأمين وآخر كشف بنكي مختوم بمبلغ 30.000 درهم على الأقل.",
    },
  },

  /* ====================================================================== */
  /*  ROYAUME-UNI                                                           */
  /* ====================================================================== */
  {
    id: "angleterre-ecosse",
    slug: "angleterre-ecosse",
    zone: ROYAUME_UNI,
    kind: "circuit",
    title: { fr: "Angleterre & Écosse", ar: "إنجلترا واسكتلندا" },
    summary: {
      fr: "Cinq nuits à Londres puis quatre à Newcastle, avec excursions en train à Édimbourg et à Durham, cathédrale classée UNESCO.",
      ar: "خمس ليالٍ في لندن ثم أربع في نيوكاسل، مع رحلات بالقطار إلى إدنبرة ودرم بكاتدرائيتها المصنّفة لدى اليونسكو.",
    },
    region: { fr: "Londres · Newcastle · Édimbourg", ar: "لندن · نيوكاسل · إدنبرة" },
    days: 10,
    nights: 9,
    priceMad: 27000,
    image: "/media/tours/angleterre-ecosse.webp",
    level: { fr: "Circuit guidé", ar: "جولة مرشدة" },
    best: { fr: "07 → 16 août 2026", ar: "07 ← 16 غشت 2026" },
    flightIncluded: true,
    airline: "Royal Air Maroc",
    departureCity: CASABLANCA,
    departures: [{ fr: "07/08 → 16/08/2026", ar: "07/08 → 16/08/2026" }],
    highlights: [
      { fr: "London Eye — entrée incluse", ar: "عين لندن — التذكرة مشمولة" },
      { fr: "Tower of London et les Joyaux de la Couronne", ar: "برج لندن وجواهر التاج" },
      { fr: "Excursion en train à Édimbourg et son château", ar: "رحلة بالقطار إلى إدنبرة وقلعتها" },
      { fr: "Durham, cathédrale normande classée UNESCO", ar: "درم، كاتدرائية نورمانية مصنّفة لدى اليونسكو" },
      { fr: "Assistance pour le dépôt du dossier de visa", ar: "مساعدة في إيداع ملفّ التأشيرة" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Arrivée à Londres", ar: "الوصول إلى لندن" }, detail: { fr: "Accueil et transfert vers l'hôtel, installation et temps libre pour une première découverte.", ar: "الاستقبال والنقل إلى الفندق، الاستقرار ووقت حرّ لأول اكتشاف." } },
      { day: 2, title: { fr: "Londres classique", ar: "لندن الكلاسيكية" }, detail: { fr: "Buckingham Palace, Westminster et Big Ben, London Eye (entrée incluse) et Trafalgar Square.", ar: "قصر باكنغهام، وستمنستر وبيغ بن، عين لندن (التذكرة مشمولة) وساحة ترافالغار." } },
      { day: 3, title: { fr: "Londres historique", ar: "لندن التاريخية" }, detail: { fr: "Tower of London et les Joyaux de la Couronne, Tower Bridge et City of London. Déjeuner buffet inclus.", ar: "برج لندن وجواهر التاج، جسر البرج ومدينة لندن المالية. غداء بوفيه مشمول." } },
      { day: 4, title: { fr: "Culture & shopping", ar: "ثقافة وتسوّق" }, detail: { fr: "British Museum et ses collections antiques, puis Oxford Street.", ar: "المتحف البريطاني ومجموعاته القديمة، ثم شارع أكسفورد." } },
      { day: 5, title: { fr: "Westfield ou journée libre", ar: "ويستفيلد أو يوم حرّ" }, detail: { fr: "Shopping à Westfield London, l'un des plus grands centres d'Europe, ou journée libre (musées, croisière sur la Tamise…).", ar: "تسوّق في ويستفيلد لندن، أحد أكبر المراكز في أوروبا، أو يوم حرّ (متاحف، جولة على نهر التايمز…)." } },
      { day: 6, title: { fr: "Londres – Newcastle", ar: "لندن – نيوكاسل" }, detail: { fr: "Départ en autocar vers le nord de l'Angleterre (≈ 3 h), installation puis promenade au Quayside le long de la Tyne.", ar: "الانطلاق بالحافلة نحو شمال إنجلترا (≈ 3 ساعات)، الاستقرار ثم نزهة في كيسايد على ضفاف نهر تاين." } },
      { day: 7, title: { fr: "City tour de Newcastle", ar: "جولة في نيوكاسل" }, detail: { fr: "Newcastle Castle, Grey Street, Tyne Bridge et le Baltic Centre for Contemporary Art.", ar: "قلعة نيوكاسل، شارع غراي، جسر تاين ومركز بالتيك للفنّ المعاصر." } },
      { day: 8, title: { fr: "Excursion à Édimbourg", ar: "رحلة إلى إدنبرة" }, detail: { fr: "Train direct (≈ 1 h 30) vers la capitale écossaise : vieille ville, Edinburgh Castle et National Museum of Scotland.", ar: "قطار مباشر (≈ ساعة ونصف) نحو العاصمة الاسكتلندية: المدينة العتيقة، قلعة إدنبرة والمتحف الوطني لاسكتلندا." } },
      { day: 9, title: { fr: "Excursion à Durham", ar: "رحلة إلى درم" }, detail: { fr: "Cathédrale classée UNESCO, Durham Castle et centre historique pavé. Dîner inclus.", ar: "الكاتدرائية المصنّفة لدى اليونسكو، قلعة درم والمركز التاريخي المرصوف. العشاء مشمول." } },
      { day: 10, title: { fr: "Newcastle – Londres – retour", ar: "نيوكاسل – لندن – العودة" }, detail: { fr: "Retour vers Londres et transfert à l'aéroport selon l'horaire du vol.", ar: "العودة نحو لندن والنقل إلى المطار حسب موعد الرحلة." } },
    ],
    hotels: [
      { city: { fr: "Londres", ar: "لندن" }, name: "Strand Palace Hotel 4*", nights: 5 },
      { city: { fr: "Newcastle", ar: "نيوكاسل" }, name: "Hotel Indigo Newcastle by IHG 4*", nights: 4 },
    ],
    pricing: [
      { label: { fr: "Chambre triple", ar: "غرفة ثلاثية" }, mad: 27000 },
      { label: { fr: "Chambre double", ar: "غرفة مزدوجة" }, mad: 27700 },
      { label: { fr: "Supplément single", ar: "زيادة الغرفة الفردية" }, mad: 8700 },
    ],
    included: [
      { fr: "Vol Royal Air Maroc en classe économique", ar: "رحلة مع الخطوط الملكية المغربية في الدرجة السياحية" },
      { fr: "9 nuits en hôtels 4* avec petits déjeuners", ar: "9 ليالٍ في فنادق 4 نجوم مع الفطور" },
      { fr: "Autocar privé climatisé entre Londres et Newcastle", ar: "حافلة خاصة مكيّفة بين لندن ونيوكاسل" },
      { fr: "Les visites, excursions et droits d'entrée mentionnés", ar: "الزيارات والرحلات وتذاكر الدخول المذكورة" },
      { fr: "Accompagnateur arabophone / francophone pendant tout le circuit", ar: "مرافق ناطق بالعربية / الفرنسية طوال الجولة" },
      { fr: "Assistance pour le dépôt du dossier de visa", ar: "مساعدة في إيداع ملفّ التأشيرة" },
    ],
    notIncluded: [
      { fr: "L'assurance voyage, vivement conseillée", ar: "تأمين السفر، ننصح به بشدّة" },
      { fr: "Les repas non mentionnés et les boissons pendant les repas", ar: "الوجبات غير المذكورة والمشروبات أثناء الوجبات" },
      { fr: "Les pourboires pour le guide et le chauffeur", ar: "إكراميات المرشد والسائق" },
      { fr: "Les excursions optionnelles", ar: "الرحلات الاختيارية" },
    ],
    flights: [
      { route: { fr: "AT 800 · Casablanca → Londres Heathrow (07 août)", ar: "AT 800 · الدار البيضاء ← لندن هيثرو (07 غشت)" }, time: "13h40 – 16h50" },
      { route: { fr: "AT 801 · Londres Heathrow → Casablanca (16 août)", ar: "AT 801 · لندن هيثرو ← الدار البيضاء (16 غشت)" }, time: "18h10 – 21h30" },
    ],
    visa: {
      fr: "Visa britannique obligatoire. L'agence assure l'assistance pour le dépôt du dossier ; les frais consulaires restent à la charge du voyageur.",
      ar: "التأشيرة البريطانية إلزامية. تتكفّل الوكالة بالمساعدة في إيداع الملفّ؛ أمّا الرسوم القنصلية فتبقى على عاتق المسافر.",
    },
  },

  /* ====================================================================== */
  /*  ITALIE — départs garantis, vol non inclus                             */
  /* ====================================================================== */
  {
    id: "italie-trio",
    slug: "italie-trio-italien",
    zone: ITALIE,
    kind: "circuit",
    title: { fr: "Le Trio Italien — Venise, Florence & Rome", ar: "الثلاثي الإيطالي — البندقية وفلورنسا وروما" },
    summary: {
      fr: "Six jours entre les trois joyaux de l'Italie, visites guidées incluses et tous les transferts en train ou autocar. Départs garantis.",
      ar: "ستّة أيام بين جواهر إيطاليا الثلاث، زيارات مرشدة مشمولة وجميع التنقّلات بالقطار أو الحافلة. انطلاقات مضمونة.",
    },
    region: { fr: "Venise · Florence · Rome", ar: "البندقية · فلورنسا · روما" },
    days: 6,
    nights: 5,
    priceMad: 9250,
    image: "/media/tours/italie-trio.webp",
    level: { fr: "Circuit guidé", ar: "جولة مرشدة" },
    best: { fr: "Départs garantis toute l'année", ar: "انطلاقات مضمونة طوال السنة" },
    flightIncluded: false,
    departures: [
      { fr: "Départs de Venise — juillet : 13→18, 25→30", ar: "انطلاقات من البندقية — يوليوز: 13→18، 25→30" },
      { fr: "Départs de Venise — août : 10→15, 24→29", ar: "انطلاقات من البندقية — غشت: 10→15، 24→29" },
      { fr: "Départs de Venise — septembre : 07→12, 21→26", ar: "انطلاقات من البندقية — شتنبر: 07→12، 21→26" },
      { fr: "Départs de Rome — un ou deux départs par mois, de janvier à décembre", ar: "انطلاقات من روما — انطلاق أو اثنان كل شهر، من يناير إلى دجنبر" },
    ],
    highlights: [
      { fr: "Place Saint-Marc, Rialto et Palais des Doges à Venise", ar: "ساحة القدّيس مرقس وريالتو وقصر الدوجي في البندقية" },
      { fr: "Ponte Vecchio et Duomo de Florence", ar: "بونتي فيكيو وكاتدرائية فلورنسا" },
      { fr: "Fontaine de Trevi, Colisée et place Saint-Pierre à Rome", ar: "نافورة تريفي والكولوسيوم وساحة القدّيس بطرس في روما" },
      { fr: "Accompagnateur francophone sur tout le circuit", ar: "مرافق ناطق بالفرنسية طوال الجولة" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Arrivée à Venise", ar: "الوصول إلى البندقية" }, detail: { fr: "Accueil à l'aéroport, transfert à l'hôtel et check-in. Dîner libre.", ar: "الاستقبال في المطار، النقل إلى الفندق وتسجيل الدخول. عشاء حرّ." } },
      { day: 2, title: { fr: "Venise — visite guidée", ar: "البندقية — زيارة مرشدة" }, detail: { fr: "Rialto, place Saint-Marc, Basilique et Palais des Doges (extérieurs). Après-midi libre, option Murano & Burano.", ar: "ريالتو، ساحة القدّيس مرقس، البازيليك وقصر الدوجي (من الخارج). بعد الظهر حرّ، مع خيار مورانو وبورانو." } },
      { day: 3, title: { fr: "Venise – Florence", ar: "البندقية – فلورنسا" }, detail: { fr: "Départ en train ou autocar, installation, puis visite guidée : Ponte Vecchio, Duomo, Piazza della Repubblica et della Signoria.", ar: "الانطلاق بالقطار أو الحافلة، الاستقرار، ثم زيارة مرشدة: بونتي فيكيو، الكاتدرائية، ساحتا الجمهورية والسينيوريا." } },
      { day: 4, title: { fr: "Florence – Rome", ar: "فلورنسا – روما" }, detail: { fr: "Transfert vers Rome, la Ville éternelle, et installation à l'hôtel. Dîner libre.", ar: "الانتقال نحو روما، المدينة الخالدة، والاستقرار بالفندق. عشاء حرّ." } },
      { day: 5, title: { fr: "Les merveilles de Rome", ar: "عجائب روما" }, detail: { fr: "Piazza di Spagna, fontaine de Trevi, Piazza Venezia, Colisée (extérieur), Forum romain, Panthéon et place Saint-Pierre.", ar: "ساحة إسبانيا، نافورة تريفي، ساحة البندقية، الكولوسيوم (من الخارج)، المنتدى الروماني، البانثيون وساحة القدّيس بطرس." } },
      { day: 6, title: { fr: "Départ de Rome", ar: "المغادرة من روما" }, detail: { fr: "Petit déjeuner, check-out et transfert à l'aéroport. Fin de nos services.", ar: "الفطور، تسجيل الخروج والنقل إلى المطار. نهاية خدماتنا." } },
    ],
    hotels: [
      { city: { fr: "Venise (Mestre)", ar: "البندقية (مستري)" }, name: "Hotel Novotel 4* / Hotel Lugano 4*", nights: 2 },
      { city: { fr: "Florence", ar: "فلورنسا" }, name: "Hotel Ambasciatori 4* / Grand Hotel Mediterraneo 4* / Hotel Diplomat 4*", nights: 1 },
      { city: { fr: "Rome", ar: "روما" }, name: "Hotel Gioberti 4* / Hotel Cristoforo Colombo 4*", nights: 2 },
    ],
    pricing: [
      { label: { fr: "Chambre triple (à partir de)", ar: "غرفة ثلاثية (ابتداءً من)" }, mad: 9250 },
      { label: { fr: "Chambre double (à partir de)", ar: "غرفة مزدوجة (ابتداءً من)" }, mad: 9450 },
      { label: { fr: "Haute saison (août) · Triple", ar: "الموسم المرتفع (غشت) · ثلاثية" }, mad: 9550 },
      { label: { fr: "Haute saison (août) · Double", ar: "الموسم المرتفع (غشت) · مزدوجة" }, mad: 9800 },
      { label: { fr: "Supplément single (à partir de)", ar: "زيادة الغرفة الفردية (ابتداءً من)" }, mad: 2600 },
    ],
    included: [
      { fr: "5 nuits en hôtels 4* avec petit déjeuner", ar: "5 ليالٍ في فنادق 4 نجوم مع الفطور" },
      { fr: "Accompagnateur francophone sur tout le circuit", ar: "مرافق ناطق بالفرنسية طوال الجولة" },
      { fr: "1 journée de visite guidée de Rome, 1/2 journée à Florence et 1/2 journée à Venise", ar: "يوم كامل من الزيارة المرشدة في روما، ونصف يوم في فلورنسا ونصف يوم في البندقية" },
      { fr: "Train Venezia Mestre – Venezia Santa Lucia", ar: "قطار البندقية مستري – البندقية سانتا لوتشيا" },
      { fr: "Tous les transferts aéroport / hôtel et entre les villes (train ou autocar)", ar: "جميع التنقّلات مطار / فندق وبين المدن (قطار أو حافلة)" },
    ],
    notIncluded: [
      { fr: "Le vol — à réserver séparément auprès de l'agence", ar: "تذكرة الطيران — تُحجز على حدة لدى الوكالة" },
      { fr: "Les repas, boissons et entrées aux monuments", ar: "الوجبات والمشروبات وتذاكر دخول المعالم" },
      { fr: "La taxe de séjour, à payer sur place", ar: "ضريبة الإقامة، تُدفع في عين المكان" },
      { fr: "L'assurance voyage et les excursions optionnelles", ar: "تأمين السفر والرحلات الاختيارية" },
    ],
    options: [
      { label: { fr: "Venise — Murano & Burano", ar: "البندقية — مورانو وبورانو" }, mad: 650 },
      { label: { fr: "Rome — entrée au Colisée", ar: "روما — تذكرة الكولوسيوم" }, mad: 350 },
    ],
  },

  {
    id: "italie-bella",
    slug: "italie-bella-italia",
    zone: ITALIE,
    kind: "circuit",
    title: { fr: "La Bella Italia — Milan, Venise, Florence & Rome", ar: "لا بيلا إيطاليا — ميلانو والبندقية وفلورنسا وروما" },
    summary: {
      fr: "Huit jours du Duomo de Milan au Panthéon de Rome, quatre villes en visites guidées et tous les transferts inclus. Départs garantis.",
      ar: "ثمانية أيام من كاتدرائية ميلانو إلى بانثيون روما، أربع مدن بزيارات مرشدة وجميع التنقّلات مشمولة. انطلاقات مضمونة.",
    },
    region: { fr: "Milan · Venise · Florence · Rome", ar: "ميلانو · البندقية · فلورنسا · روما" },
    days: 8,
    nights: 7,
    priceMad: 11550,
    image: "/media/tours/italie-bella.webp",
    level: { fr: "Circuit guidé", ar: "جولة مرشدة" },
    best: { fr: "Départs garantis toute l'année", ar: "انطلاقات مضمونة طوال السنة" },
    flightIncluded: false,
    departures: [
      { fr: "Départs de Rome — deux départs par mois, de janvier à décembre", ar: "انطلاقات من روما — انطلاقان كل شهر، من يناير إلى دجنبر" },
      { fr: "Départs de Milan — juillet : 25/07 → 01/08", ar: "انطلاقات من ميلانو — يوليوز: 25/07 → 01/08" },
      { fr: "Départs de Milan — août : 08→15, 22→29", ar: "انطلاقات من ميلانو — غشت: 08→15، 22→29" },
      { fr: "Départs de Milan — septembre : 05→12, 19→26", ar: "انطلاقات من ميلانو — شتنبر: 05→12، 19→26" },
    ],
    highlights: [
      { fr: "Duomo de Milan et Galleria Vittorio Emanuele II", ar: "كاتدرائية ميلانو ورواق فيتوريو إيمانويلي الثاني" },
      { fr: "Place Saint-Marc et Rialto à Venise", ar: "ساحة القدّيس مرقس وريالتو في البندقية" },
      { fr: "Ponte Vecchio et Piazza della Signoria à Florence", ar: "بونتي فيكيو وساحة السينيوريا في فلورنسا" },
      { fr: "Journée entièrement libre à Rome", ar: "يوم كامل حرّ في روما" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Arrivée à Milan", ar: "الوصول إلى ميلانو" }, detail: { fr: "Accueil à l'aéroport de Milan Malpensa, transfert à l'hôtel et installation. Dîner libre.", ar: "الاستقبال في مطار ميلانو مالبينسا، النقل إلى الفندق والاستقرار. عشاء حرّ." } },
      { day: 2, title: { fr: "Milan — visite guidée", ar: "ميلانو — زيارة مرشدة" }, detail: { fr: "Duomo, Galleria Vittorio Emanuele II, théâtre de la Scala et château des Sforza (extérieurs). Après-midi libre.", ar: "الكاتدرائية، رواق فيتوريو إيمانويلي الثاني، مسرح لا سكالا وقلعة سفورتسا (من الخارج). بعد الظهر حرّ." } },
      { day: 3, title: { fr: "Milan – Venise", ar: "ميلانو – البندقية" }, detail: { fr: "Transfert vers Venise Mestre en train ou autocar, installation à l'hôtel et après-midi libre.", ar: "الانتقال نحو البندقية مستري بالقطار أو الحافلة، الاستقرار بالفندق وبعد الظهر حرّ." } },
      { day: 4, title: { fr: "Venise — visite guidée", ar: "البندقية — زيارة مرشدة" }, detail: { fr: "Train jusqu'à Santa Lucia, puis Rialto, place Saint-Marc, Basilique et Palais des Doges (extérieurs). Option Murano & Burano.", ar: "القطار حتى سانتا لوتشيا، ثم ريالتو وساحة القدّيس مرقس والبازيليك وقصر الدوجي (من الخارج). خيار مورانو وبورانو." } },
      { day: 5, title: { fr: "Venise – Florence", ar: "البندقية – فلورنسا" }, detail: { fr: "Départ pour Florence, installation puis visite guidée : Ponte Vecchio, Duomo, Piazza della Signoria et della Repubblica.", ar: "الانطلاق نحو فلورنسا، الاستقرار ثم زيارة مرشدة: بونتي فيكيو والكاتدرائية وساحتا السينيوريا والجمهورية." } },
      { day: 6, title: { fr: "Florence – Rome", ar: "فلورنسا – روما" }, detail: { fr: "Transfert vers Rome et visite guidée : Piazza di Spagna, fontaine de Trevi, Piazza Venezia, Colisée (extérieur), Forum romain et Panthéon.", ar: "الانتقال نحو روما وزيارة مرشدة: ساحة إسبانيا، نافورة تريفي، ساحة البندقية، الكولوسيوم (من الخارج)، المنتدى الروماني والبانثيون." } },
      { day: 7, title: { fr: "Rome — journée libre", ar: "روما — يوم حرّ" }, detail: { fr: "Journée entièrement libre. Excursions optionnelles possibles : Musées du Vatican, Castel Romano.", ar: "يوم حرّ بالكامل. رحلات اختيارية ممكنة: متاحف الفاتيكان، كاستل رومانو." } },
      { day: 8, title: { fr: "Départ de Rome", ar: "المغادرة من روما" }, detail: { fr: "Petit déjeuner, check-out et transfert vers l'aéroport de Rome. Fin de nos services.", ar: "الفطور، تسجيل الخروج والنقل إلى مطار روما. نهاية خدماتنا." } },
    ],
    hotels: [
      { city: { fr: "Milan", ar: "ميلانو" }, name: "Hotel Nyx 4* / ADI Doria Grand Hotel 4* / Leonardo City Center 4*", nights: 2 },
      { city: { fr: "Venise (Mestre)", ar: "البندقية (مستري)" }, name: "Hotel Lugano 4* / BW Bologna 4* / Novotel 4*", nights: 2 },
      { city: { fr: "Florence", ar: "فلورنسا" }, name: "Hotel Ambasciatori 4* / Hotel Diplomat 4*", nights: 1 },
      { city: { fr: "Rome", ar: "روما" }, name: "Hotel Gioberti 4* / Cristoforo Colombo 4*", nights: 2 },
    ],
    pricing: [
      { label: { fr: "Basse saison · Triple", ar: "الموسم المنخفض · ثلاثية" }, mad: 11550 },
      { label: { fr: "Basse saison · Double", ar: "الموسم المنخفض · مزدوجة" }, mad: 11750 },
      { label: { fr: "Haute saison (août) · Triple", ar: "الموسم المرتفع (غشت) · ثلاثية" }, mad: 13200 },
      { label: { fr: "Haute saison (août) · Double", ar: "الموسم المرتفع (غشت) · مزدوجة" }, mad: 13350 },
      { label: { fr: "Supplément single (à partir de)", ar: "زيادة الغرفة الفردية (ابتداءً من)" }, mad: 3600 },
    ],
    included: [
      { fr: "7 nuits en hôtels 4* avec petit déjeuner", ar: "7 ليالٍ في فنادق 4 نجوم مع الفطور" },
      { fr: "Accompagnateur pour tout le circuit", ar: "مرافق طوال الجولة" },
      { fr: "Visites guidées de Milan, Venise, Florence et Rome", ar: "زيارات مرشدة في ميلانو والبندقية وفلورنسا وروما" },
      { fr: "Train Mestre – Santa Lucia et tous les transferts entre villes", ar: "قطار مستري – سانتا لوتشيا وجميع التنقّلات بين المدن" },
      { fr: "Transferts aéroport / hôtel et assistance pendant tout le voyage", ar: "التنقّلات مطار / فندق والمساعدة طوال الرحلة" },
    ],
    notIncluded: [
      { fr: "Le vol — à réserver séparément auprès de l'agence", ar: "تذكرة الطيران — تُحجز على حدة لدى الوكالة" },
      { fr: "Les repas, boissons et entrées aux monuments", ar: "الوجبات والمشروبات وتذاكر دخول المعالم" },
      { fr: "La taxe de séjour, à payer sur place", ar: "ضريبة الإقامة، تُدفع في عين المكان" },
      { fr: "L'assurance voyage et les excursions optionnelles", ar: "تأمين السفر والرحلات الاختيارية" },
    ],
    options: [
      { label: { fr: "Venise — Murano & Burano", ar: "البندقية — مورانو وبورانو" }, mad: 650 },
      { label: { fr: "Rome — entrée au Colisée", ar: "روما — تذكرة الكولوسيوم" }, mad: 350 },
      { label: { fr: "Rome — Musées du Vatican", ar: "روما — متاحف الفاتيكان" }, mad: 380 },
      { label: { fr: "Rome — Castel Romano", ar: "روما — كاستل رومانو" }, mad: 270 },
    ],
  },

  {
    id: "italie-tresors",
    slug: "italie-tresors-d-italie",
    zone: ITALIE,
    kind: "circuit",
    title: { fr: "Trésors d'Italie — Naples, Rome, Florence & Venise", ar: "كنوز إيطاليا — نابولي وروما وفلورنسا والبندقية" },
    summary: {
      fr: "Huit jours du golfe de Naples à la lagune de Venise, avec le Colisée et le Vatican en visite guidée. Départs garantis.",
      ar: "ثمانية أيام من خليج نابولي إلى بحيرة البندقية، مع الكولوسيوم والفاتيكان بزيارة مرشدة. انطلاقات مضمونة.",
    },
    region: { fr: "Naples · Rome · Florence · Venise", ar: "نابولي · روما · فلورنسا · البندقية" },
    days: 8,
    nights: 7,
    priceMad: 11500,
    image: "/media/tours/italie-tresors.webp",
    level: { fr: "Circuit guidé", ar: "جولة مرشدة" },
    best: { fr: "Départs garantis toute l'année", ar: "انطلاقات مضمونة طوال السنة" },
    flightIncluded: false,
    departures: [
      { fr: "Départs de Naples — deux départs par mois, de janvier à décembre", ar: "انطلاقات من نابولي — انطلاقان كل شهر، من يناير إلى دجنبر" },
      { fr: "Départs de Venise — juillet : 13→20, 25→01/08", ar: "انطلاقات من البندقية — يوليوز: 13→20، 25/07 → 01/08" },
      { fr: "Départs de Venise — août : 10→17, 24→31", ar: "انطلاقات من البندقية — غشت: 10→17، 24→31" },
      { fr: "Départs de Venise — septembre : 07→14, 21→28", ar: "انطلاقات من البندقية — شتنبر: 07→14، 21→28" },
    ],
    highlights: [
      { fr: "Colisée, Forum romain et mont Palatin en visite guidée", ar: "الكولوسيوم والمنتدى الروماني وتلّة بالاتينو بزيارة مرشدة" },
      { fr: "Basilique Saint-Pierre au Vatican", ar: "بازيليك القدّيس بطرس في الفاتيكان" },
      { fr: "Côte amalfitaine et Pompéi en option", ar: "ساحل أمالفي وبومبي كخيار" },
      { fr: "Place Saint-Marc et Pont des Soupirs à Venise", ar: "ساحة القدّيس مرقس وجسر التنهّدات في البندقية" },
    ],
    itinerary: [
      { day: 1, title: { fr: "Arrivée à Naples", ar: "الوصول إلى نابولي" }, detail: { fr: "Accueil à l'aéroport ou à la gare, transfert et installation à l'hôtel 4*. Temps libre.", ar: "الاستقبال في المطار أو المحطّة، النقل والاستقرار في فندق 4 نجوم. وقت حرّ." } },
      { day: 2, title: { fr: "Pompéi & côte amalfitaine (option)", ar: "بومبي وساحل أمالفي (اختياري)" }, detail: { fr: "Excursion guidée à Pompéi puis route le long de la côte amalfitaine : Sorrente et Positano. Retour à Naples.", ar: "رحلة مرشدة إلى بومبي ثم الطريق على ساحل أمالفي: سورينتو وبوزيتانو. العودة إلى نابولي." } },
      { day: 3, title: { fr: "Naples – Rome", ar: "نابولي – روما" }, detail: { fr: "Bus privé ou train rapide vers Rome (2 h 30), installation puis découverte guidée : fontaine de Trevi, Piazza Navona et Panthéon.", ar: "حافلة خاصة أو قطار سريع نحو روما (ساعتان ونصف)، الاستقرار ثم اكتشاف مرشد: نافورة تريفي وساحة نافونا والبانثيون." } },
      { day: 4, title: { fr: "Rome antique & Vatican", ar: "روما القديمة والفاتيكان" }, detail: { fr: "Visite guidée du Colisée, du Forum romain et du mont Palatin, puis basilique Saint-Pierre. Option Musées du Vatican et chapelle Sixtine.", ar: "زيارة مرشدة للكولوسيوم والمنتدى الروماني وتلّة بالاتينو، ثم بازيليك القدّيس بطرس. خيار متاحف الفاتيكان وكنيسة سيستينا." } },
      { day: 5, title: { fr: "Rome – Florence", ar: "روما – فلورنسا" }, detail: { fr: "Départ en bus ou train rapide, puis visite guidée : Duomo, Baptistère, Piazza della Signoria et Ponte Vecchio.", ar: "الانطلاق بالحافلة أو القطار السريع، ثم زيارة مرشدة: الكاتدرائية والمعمودية وساحة السينيوريا وبونتي فيكيو." } },
      { day: 6, title: { fr: "Florence – Venise", ar: "فلورنسا – البندقية" }, detail: { fr: "Route vers Venise (2 h), installation puis découverte : place Saint-Marc, Basilique et Pont des Soupirs. Option balade en gondole au coucher du soleil.", ar: "الطريق نحو البندقية (ساعتان)، الاستقرار ثم الاكتشاف: ساحة القدّيس مرقس والبازيليك وجسر التنهّدات. خيار جولة بالغندول عند الغروب." } },
      { day: 7, title: { fr: "Venise — Murano & Burano (option)", ar: "البندقية — مورانو وبورانو (اختياري)" }, detail: { fr: "Excursion guidée en bateau : soufflage du verre à Murano, maisons colorées et dentelle à Burano. Temps libre à Venise.", ar: "رحلة بحرية مرشدة: نفخ الزجاج في مورانو، البيوت الملوّنة والدانتيل في بورانو. وقت حرّ في البندقية." } },
      { day: 8, title: { fr: "Départ de Venise", ar: "المغادرة من البندقية" }, detail: { fr: "Petit déjeuner puis transfert vers l'aéroport ou la gare de Venise. Fin de nos services.", ar: "الفطور ثم النقل إلى مطار أو محطّة البندقية. نهاية خدماتنا." } },
    ],
    hotels: [
      { city: { fr: "Naples", ar: "نابولي" }, name: "Ramada 4* / Hotel Tritone 4*", nights: 2 },
      { city: { fr: "Rome", ar: "روما" }, name: "Hotel Gioberti 4* / Cristoforo Colombo 4*", nights: 2 },
      { city: { fr: "Florence", ar: "فلورنسا" }, name: "Hotel Ambasciatori 4* / Hotel Diplomat 4*", nights: 1 },
      { city: { fr: "Venise (Mestre)", ar: "البندقية (مستري)" }, name: "Hotel BW Bologna 4* / Novotel 4*", nights: 2 },
    ],
    pricing: [
      { label: { fr: "Basse saison · Triple", ar: "الموسم المنخفض · ثلاثية" }, mad: 11500 },
      { label: { fr: "Basse saison · Double", ar: "الموسم المنخفض · مزدوجة" }, mad: 11750 },
      { label: { fr: "Haute saison (août) · Triple", ar: "الموسم المرتفع (غشت) · ثلاثية" }, mad: 13200 },
      { label: { fr: "Haute saison (août) · Double", ar: "الموسم المرتفع (غشت) · مزدوجة" }, mad: 13350 },
      { label: { fr: "Supplément single (à partir de)", ar: "زيادة الغرفة الفردية (ابتداءً من)" }, mad: 3500 },
    ],
    included: [
      { fr: "7 nuits en hôtels 4* avec petit déjeuner", ar: "7 ليالٍ في فنادق 4 نجوم مع الفطور" },
      { fr: "Accompagnateur pour tout le circuit", ar: "مرافق طوال الجولة" },
      { fr: "Visites guidées de Naples, Rome, Florence et Venise", ar: "زيارات مرشدة في نابولي وروما وفلورنسا والبندقية" },
      { fr: "Tous les transferts entre villes (train ou autocar)", ar: "جميع التنقّلات بين المدن (قطار أو حافلة)" },
      { fr: "Transfert aéroport / hôtel et assistance pendant tout le voyage", ar: "النقل مطار / فندق والمساعدة طوال الرحلة" },
    ],
    notIncluded: [
      { fr: "Le vol — à réserver séparément auprès de l'agence", ar: "تذكرة الطيران — تُحجز على حدة لدى الوكالة" },
      { fr: "Les repas, boissons et entrées aux monuments", ar: "الوجبات والمشروبات وتذاكر دخول المعالم" },
      { fr: "Les taxes de séjour et les pourboires", ar: "ضرائب الإقامة والإكراميات" },
      { fr: "L'assurance voyage et les excursions optionnelles", ar: "تأمين السفر والرحلات الاختيارية" },
    ],
    options: [
      { label: { fr: "Naples — Pompéi & Amalfi", ar: "نابولي — بومبي وأمالفي" }, mad: 2150 },
      { label: { fr: "Venise — Murano & Burano", ar: "البندقية — مورانو وبورانو" }, mad: 650 },
      { label: { fr: "Rome — Musées du Vatican", ar: "روما — متاحف الفاتيكان" }, mad: 380 },
      { label: { fr: "Venise — balade en gondole au coucher du soleil", ar: "البندقية — جولة بالغندول عند الغروب" }, mad: 270 },
    ],
  },
];
